import Mathlib.Tactic
import QEC.Stabilizer.Core.StabilizerGroup
import QEC.Stabilizer.Core.SubgroupLemmas
import QEC.Stabilizer.Core.CSSPredicates
import QEC.Stabilizer.Core.CSSNoNegI
import QEC.Stabilizer.Core.Centralizer
import QEC.Stabilizer.Core.CSSCommutationLemmas
import QEC.Stabilizer.Core.CodeDistance
import QEC.Stabilizer.Core.LogicalOperators
import QEC.Stabilizer.Core.StabilizerCode
import QEC.Stabilizer.PauliGroup.Commutation
import QEC.Stabilizer.PauliGroup.CommutationTactics
import QEC.Stabilizer.PauliGroup.NQubitOperator
import QEC.Stabilizer.PauliGroup.NQubitElement
import QEC.Stabilizer.BinarySymplectic.Core
import QEC.Stabilizer.BinarySymplectic.CheckMatrix
import QEC.Stabilizer.BinarySymplectic.CheckMatrixDecidable
import QEC.Stabilizer.BinarySymplectic.IndependentEquiv

namespace Quantum
open scoped BigOperators

namespace StabilizerGroup
namespace FourQubit_4_2_2

/-!
# The [[4, 2, 2]] four-qubit code (also known as `C₄` or "Little Shor code")

A four-qubit hyperbolic self-dual CSS detection code with **two logical qubits**
and distance 2. Originally introduced in
[Vaidman–Goldenberg–Wiesner 1996, `arxiv:quant-ph/9603031`] and
[Grassl–Beth–Pellizzari 1996, `arxiv:quant-ph/9610042`].

The stabilizer is generated by two operators: `XXXX` and `ZZZZ`. The four
codeword basis states are
```
|0̄0̄⟩ = (|0000⟩ + |1111⟩)/√2
|0̄1̄⟩ = (|0011⟩ + |1100⟩)/√2
|1̄0̄⟩ = (|0101⟩ + |1010⟩)/√2
|1̄1̄⟩ = (|0110⟩ + |1001⟩)/√2
```
giving logical operators
```
X̄₁ = IXIX,  X̄₂ = IIXX,  Z̄₁ = IIZZ,  Z̄₂ = IZIZ.
```

This file is a **Stage-2 skeleton**: every theorem ends in a `sorry` tagged
`TODO(stab_4_2_2-T<n>): …`. Stage 4 closes them following the Steane7
template, scaled down to 4 qubits and adapted for k = 2.
-/

open NQubitPauliGroupElement

/-! ## Generators -/

/-- Z-check stabilizer: `ZZZZ` (Z on every qubit). -/
def Z1 : NQubitPauliGroupElement 4 :=
  ⟨0,
    (((NQubitPauliOperator.identity 4).set 0 PauliOperator.Z).set 1 PauliOperator.Z).set 2
      PauliOperator.Z |>.set 3 PauliOperator.Z⟩

/-- X-check stabilizer: `XXXX` (X on every qubit). -/
def X1 : NQubitPauliGroupElement 4 :=
  ⟨0,
    (((NQubitPauliOperator.identity 4).set 0 PauliOperator.X).set 1 PauliOperator.X).set 2
      PauliOperator.X |>.set 3 PauliOperator.X⟩

/-- The single Z-check generator. -/
def ZGenerators : Set (NQubitPauliGroupElement 4) :=
  {Z1}

/-- The single X-check generator. -/
def XGenerators : Set (NQubitPauliGroupElement 4) :=
  {X1}

/-- The full generator set: one Z-check and one X-check. -/
def generators : Set (NQubitPauliGroupElement 4) :=
  ZGenerators ∪ XGenerators

/-- The [[4, 2, 2]] stabilizer subgroup: closure of `{ZZZZ, XXXX}`. -/
noncomputable def subgroup : Subgroup (NQubitPauliGroupElement 4) :=
  Subgroup.closure generators

/-! ## Typing facts: Z-type / X-type generators -/

/-- The Z-generator is Z-type (I or Z on every qubit). -/
lemma ZGenerators_are_ZType :
    ∀ g, g ∈ ZGenerators → NQubitPauliGroupElement.IsZTypeElement g := by
  sorry  -- TODO(stab_4_2_2-T1): rcases hg → rfl; constructor with phase=0 and fin_cases on Fin 4.

/-- The X-generator is X-type (I or X on every qubit). -/
lemma XGenerators_are_XType :
    ∀ g, g ∈ XGenerators → NQubitPauliGroupElement.IsXTypeElement g := by
  sorry  -- TODO(stab_4_2_2-T2): rcases hg → rfl; constructor with phase=0 and fin_cases on Fin 4.

/-! ## Cross-commutation: Z generators commute with X generators

`ZZZZ` and `XXXX` overlap at all 4 qubits, so they anticommute pairwise at all 4
positions — count is 4 (even) ⇒ commute. -/

private lemma Z1_comm_X1 : Z1 * X1 = X1 * Z1 := by
  sorry
  -- TODO(stab_4_2_2-T3a): pauli_comm_even_anticommutes + hfilter = {0,1,2,3} (cardinality 4).

/-- The unique Z-generator commutes with the unique X-generator (the only cross
case for this CSS code). -/
lemma ZGenerators_commute_XGenerators :
    ∀ z ∈ ZGenerators, ∀ x ∈ XGenerators, z * x = x * z := by
  sorry  -- TODO(stab_4_2_2-T3): unfold the singletons, reduce to Z1_comm_X1.

/-! ## Pairwise commutation of all generators -/

private lemma ZType_commutes {g h : NQubitPauliGroupElement 4}
    (hg : NQubitPauliGroupElement.IsZTypeElement g)
    (hh : NQubitPauliGroupElement.IsZTypeElement h) :
    g * h = h * g :=
  CSSCommutationLemmas.ZType_commutes hg hh

private lemma XType_commutes {g h : NQubitPauliGroupElement 4}
    (hg : NQubitPauliGroupElement.IsXTypeElement g)
    (hh : NQubitPauliGroupElement.IsXTypeElement h) :
    g * h = h * g :=
  CSSCommutationLemmas.XType_commutes hg hh

/-- All generators of the [[4, 2, 2]] code pairwise commute. -/
theorem generators_commute :
    ∀ g ∈ generators, ∀ h ∈ generators, g * h = h * g := by
  sorry
  -- TODO(stab_4_2_2-T4): union case-split → reduce to ZType_commutes / XType_commutes /
  -- ZGenerators_commute_XGenerators (Steane7:260 pattern).

/-! ## No `-I` in the stabilizer subgroup -/

/-- The [[4, 2, 2]] stabilizer subgroup does not contain `-I` (CSS argument). -/
theorem negIdentity_not_mem :
    negIdentity 4 ∉ subgroup := by
  sorry
  -- TODO(stab_4_2_2-T5): apply CSS.negIdentity_not_mem_closure_union with the three
  -- hypotheses ZGenerators_are_ZType, XGenerators_are_XType,
  -- ZGenerators_commute_XGenerators (Steane7:277 pattern).

/-! ## Generator list & symplectic-side independence -/

/-- The generator list (canonical order: Z-check first, then X-check). -/
def generatorsList : List (NQubitPauliGroupElement 4) :=
  [Z1, X1]

/-- The generator list and the generator set agree. -/
lemma listToSet_generatorsList :
    NQubitPauliGroupElement.listToSet generatorsList = generators := by
  sorry
  -- TODO(stab_4_2_2-T6a): simp [generatorsList, generators, ZGenerators, XGenerators,
  -- listToSet_cons, listToSet_nil]; ext; tauto.

/-- All generators have phase 0 (no `i` or `−1` factor). -/
lemma AllPhaseZero_generatorsList :
    NQubitPauliGroupElement.AllPhaseZero generatorsList := by
  sorry
  -- TODO(stab_4_2_2-T7): two AllPhaseZero_cons unfoldings (Steane7:320 pattern, smaller).

/-- The check-matrix rows of the two generators are linearly independent over ℤ/2. -/
theorem rowsLinearIndependent_generatorsList :
    NQubitPauliGroupElement.rowsLinearIndependent generatorsList := by
  sorry  -- TODO(stab_4_2_2-T6b): decide (or native_decide).

/-- The generator list is an independent generating set. -/
theorem GeneratorsIndependent_4_generatorsList :
    GeneratorsIndependent 4 generatorsList :=
  GeneratorsIndependent_of_rowsLinearIndependent 4 generatorsList
    rowsLinearIndependent_generatorsList

/-! ## Bundled `StabilizerGroup 4` -/

/-- The [[4, 2, 2]] stabilizer group, from the generator list. -/
noncomputable def stabilizerGroup : StabilizerGroup 4 :=
  mkStabilizerFromGenerators 4 generatorsList
    (by rw [listToSet_generatorsList]; exact generators_commute)
    (by rw [listToSet_generatorsList]; exact negIdentity_not_mem)

lemma stabilizerGroup_toSubgroup_eq :
    stabilizerGroup.toSubgroup = subgroup := by
  sorry
  -- TODO(stab_4_2_2-T6c): simp [stabilizerGroup, mkStabilizerFromGenerators, subgroup];
  -- rw [listToSet_generatorsList].

/-! ## Logical operators

The four logical operators consistent with the codeword basis above:
- `X̄₁ = IXIX` (flips logical bit 1)
- `X̄₂ = IIXX` (flips logical bit 2)
- `Z̄₁ = IIZZ` (measures logical bit 1)
- `Z̄₂ = IZIZ` (measures logical bit 2)
-/

/-- Logical X for logical qubit 1: `IXIX`. -/
def logicalX_1 : NQubitPauliGroupElement 4 :=
  ⟨0, ((NQubitPauliOperator.identity 4).set 1 PauliOperator.X).set 3 PauliOperator.X⟩

/-- Logical X for logical qubit 2: `IIXX`. -/
def logicalX_2 : NQubitPauliGroupElement 4 :=
  ⟨0, ((NQubitPauliOperator.identity 4).set 2 PauliOperator.X).set 3 PauliOperator.X⟩

/-- Logical Z for logical qubit 1: `IIZZ`. -/
def logicalZ_1 : NQubitPauliGroupElement 4 :=
  ⟨0, ((NQubitPauliOperator.identity 4).set 2 PauliOperator.Z).set 3 PauliOperator.Z⟩

/-- Logical Z for logical qubit 2: `IZIZ`. -/
def logicalZ_2 : NQubitPauliGroupElement 4 :=
  ⟨0, ((NQubitPauliOperator.identity 4).set 1 PauliOperator.Z).set 3 PauliOperator.Z⟩

/-! ### Diagonal anticommutation: X̄_ℓ anticommutes Z̄_ℓ -/

/-- `X̄₁` and `Z̄₁` anticommute (overlap at qubit 3 only — odd parity). -/
theorem logicalX_1_anticommutes_logicalZ_1 :
    NQubitPauliGroupElement.Anticommute logicalX_1 logicalZ_1 := by
  sorry
  -- TODO(stab_4_2_2-T8a): operator-level anticommute; use commutes_iff_even_anticommutes
  -- contrapositive with hfilter = {3} (cardinality 1, odd).

/-- `X̄₂` and `Z̄₂` anticommute (overlap at qubit 3 only — odd parity). -/
theorem logicalX_2_anticommutes_logicalZ_2 :
    NQubitPauliGroupElement.Anticommute logicalX_2 logicalZ_2 := by
  sorry  -- TODO(stab_4_2_2-T8b): same pattern as T8a, hfilter = {3}.

/-! ### Off-diagonal logical commutation (the k = 2 novelty) -/

/-- `X̄₁` and `X̄₂` commute (both X-type — trivial). -/
theorem logicalX_1_commutes_logicalX_2 :
    logicalX_1 * logicalX_2 = logicalX_2 * logicalX_1 := by
  sorry  -- TODO(stab_4_2_2-T9a): pauli_comm_componentwise on X-types.

/-- `X̄₁` and `Z̄₂` commute (anticommute at qubits 1 and 3, count 2 = even). -/
theorem logicalX_1_commutes_logicalZ_2 :
    logicalX_1 * logicalZ_2 = logicalZ_2 * logicalX_1 := by
  sorry
  -- TODO(stab_4_2_2-T9b): pauli_comm_even_anticommutes + hfilter = {1, 3}.

/-- `X̄₂` and `Z̄₁` commute (anticommute at qubits 2 and 3, count 2 = even). -/
theorem logicalX_2_commutes_logicalZ_1 :
    logicalX_2 * logicalZ_1 = logicalZ_1 * logicalX_2 := by
  sorry
  -- TODO(stab_4_2_2-T9c): pauli_comm_even_anticommutes + hfilter = {2, 3}.

/-- `Z̄₁` and `Z̄₂` commute (both Z-type — trivial). -/
theorem logicalZ_1_commutes_logicalZ_2 :
    logicalZ_1 * logicalZ_2 = logicalZ_2 * logicalZ_1 := by
  sorry  -- TODO(stab_4_2_2-T9d): pauli_comm_componentwise on Z-types.

/-! ### Logical operators are in the centralizer -/

/-- `X̄₁ = IXIX` commutes with every element of the stabilizer (vs. `ZZZZ` even
overlap at qubits 1, 3; vs. `XXXX` all X — both commute). -/
theorem logicalX_1_mem_centralizer :
    logicalX_1 ∈ centralizer stabilizerGroup := by
  sorry
  -- TODO(stab_4_2_2-T10a): Steane7:413 pattern. Reduce via
  -- mem_centralizer_iff + Subgroup.forall_comm_closure_iff to two cases (Z1, X1).
  -- For X̄₁-Z1 = IXIX vs ZZZZ: pauli_comm_even_anticommutes, hfilter = {1, 3}.
  -- For X̄₁-X1: pauli_comm_componentwise (both X-supported on overlap).

/-- `X̄₂ = IIXX` commutes with every element of the stabilizer. -/
theorem logicalX_2_mem_centralizer :
    logicalX_2 ∈ centralizer stabilizerGroup := by
  sorry
  -- TODO(stab_4_2_2-T10b): same as T10a. hfilter for X̄₂ vs ZZZZ = {2, 3}; X̄₂ vs XXXX trivial.

/-- `Z̄₁ = IIZZ` commutes with every element of the stabilizer. -/
theorem logicalZ_1_mem_centralizer :
    logicalZ_1 ∈ centralizer stabilizerGroup := by
  sorry
  -- TODO(stab_4_2_2-T11a): hfilter for Z̄₁ vs XXXX = {2, 3}; Z̄₁ vs ZZZZ trivial.

/-- `Z̄₂ = IZIZ` commutes with every element of the stabilizer. -/
theorem logicalZ_2_mem_centralizer :
    logicalZ_2 ∈ centralizer stabilizerGroup := by
  sorry
  -- TODO(stab_4_2_2-T11b): hfilter for Z̄₂ vs XXXX = {1, 3}; Z̄₂ vs ZZZZ trivial.

/-! ## StabilizerCode packaging [[4, 2]] -/

/-- The two-logical-qubit `LogicalQubitOps` family. -/
private def logicalOps4_2_2 : Fin 2 → LogicalQubitOps 4 stabilizerGroup := fun ℓ =>
  match ℓ with
  | 0 => ⟨logicalX_1, logicalZ_1,
            logicalX_1_mem_centralizer, logicalZ_1_mem_centralizer,
            logicalX_1_anticommutes_logicalZ_1⟩
  | 1 => ⟨logicalX_2, logicalZ_2,
            logicalX_2_mem_centralizer, logicalZ_2_mem_centralizer,
            logicalX_2_anticommutes_logicalZ_2⟩

/-- The [[4, 2, 2]] code as a stabilizer code on 4 physical qubits with 2 logical qubits. -/
noncomputable def stabilizerCode : StabilizerCode 4 2 where
  hk := by decide
  generatorsList := generatorsList
  generators_length := rfl
  generators_phaseZero := AllPhaseZero_generatorsList
  generators_independent := GeneratorsIndependent_4_generatorsList
  generators_commute := by rw [listToSet_generatorsList]; exact generators_commute
  closure_no_neg_identity := by rw [listToSet_generatorsList]; exact negIdentity_not_mem
  logicalOps := logicalOps4_2_2
  logical_commute_cross := by
    sorry
    -- TODO(stab_4_2_2-T12): case-split on (ℓ, ℓ' : Fin 2). The only non-trivial cases
    -- are (0, 1) and (1, 0). In each case unfold logicalOps4_2_2 and dispatch the
    -- ∧-of-4 equations to the four off-diagonal lemmas T9a–T9d plus their `.symm`.

/-! ## Code distance = 2 -/

/-- The [[4, 2, 2]] code has distance 2: every weight-1 single-qubit Pauli
anticommutes with at least one of `ZZZZ` or `XXXX`, and `X̄₁ = IXIX` is a
nontrivial logical operator of weight exactly 2. -/
theorem code_has_distance_two : HasCodeDistance stabilizerCode 2 := by
  sorry
  -- TODO(stab_4_2_2-T13): apply hasCodeDistance_of with:
  --   hd: 2 ≥ 1 by decide;
  --   h_witness: X̄₁ at weight 2 (LogicalQubitOps.xOp_nontrivial of logicalOps4_2_2 0);
  --   h_min: enumerate 12 weight-1 Paulis (3 Paulis × 4 qubits) → each anticommutes with
  --     XXXX or ZZZZ → not in centralizer → not nontrivial logical.
  -- Try `native_decide` over the full `h_min` predicate first; fall back to
  -- per-case anticommutes_imp_not_isPauliLogicalOperator if needed.

end FourQubit_4_2_2
end StabilizerGroup
end Quantum
