/-
# Class base floor: bb_108 = [[108,8,10]] on `Z9 × Z6` — d ≥ 6 in strong form

Instance of the parametric small-cycle bundle
(`Framework/Homological/BBSmallCycle.lean`): every nonzero 1-cycle of the
bb_108 complex has weight ≥ 6.  Exported corollaries: the chain floor on
nontrivial cycles, the dual floor, the Pauli-level logical floor, and the
stabilizer-weight floor.

The code is a certified member of the class small-cycle theorem
(A16 write-up of record; certifier
`qec-lab:experiments/bb_lab/scripts/a15_class_certify.py`), so the four finite
obligations discharged below by `native_decide` are its engineering-grade
leaves.
True SAT distance d = 10; the class theorem certifies the analytic floor
6.

Polynomials (exponent pairs (x, y)): `A = x^3 + y + y^2`, `B = y^3 + x + x^2`.

Generated by `qec-lab:experiments/bb_lab/scripts/gen_base_floor_lean.py`
(run from a sibling qec-lab checkout with QECLEAN_ROOT pointing here); the
polynomial data is machine-written — regenerate rather than hand-edit.
-/

import QEC.Stabilizer.Framework.Homological.BBSmallCycle

namespace Quantum
namespace Stabilizer
namespace Homological
namespace BB
namespace BB108

/-- The group `Z9 × Z6`. -/
abbrev G54 : Type := ZMod 9 × ZMod 6

/-- `A = x^3 + y + y^2`. -/
def a108 : G54 → ZMod 2 := fun g =>
  if g = (0, 1) ∨ g = (0, 2) ∨ g = (3, 0) then 1 else 0

/-- `B = y^3 + x + x^2`. -/
def b108 : G54 → ZMod 2 := fun g =>
  if g = (0, 3) ∨ g = (1, 0) ∨ g = (2, 0) then 1 else 0

/-- The bb_108 chain complex. -/
noncomputable def bb108Complex : HomologicalCode := bbChainComplex a108 b108

theorem bb108Complex_numQubits : bb108Complex.numQubits = 108 := by
  change bbNumQubits G54 = 108
  unfold bbNumQubits
  rw [Fintype.card_prod, ZMod.card, ZMod.card]

/-! The four finite obligations, one declaration each (each `native_decide`
gets its own heartbeat budget — bundling them into the structure literal
blows the single-declaration limit on the larger groups). -/

/-- `ε(A) = 1`. -/
lemma epsA_holds : ∑ h : G54, a108 h = 1 := by native_decide

/-- `ε(B) = 1`. -/
lemma epsB_holds : ∑ h : G54, b108 h = 1 := by native_decide

/-- No normalized weight-2 cycle. -/
lemma check_two_holds : ∀ b : Fin 2, ∀ q : G54 × Fin 2,
    q ≠ ((0 : G54), b) →
    ∃ h : G54, SmallCycle.termAt a108 b108 ((0 : G54), b) h
      + SmallCycle.termAt a108 b108 q h ≠ 0 := by
  native_decide

/-- No normalized weight-4 cycle (tuple form; colliding tuples cancel to
the weight-2 shape). -/
lemma check_four_holds : ∀ b : Fin 2, ∀ q₁ q₂ q₃ : G54 × Fin 2,
    q₁ = ((0 : G54), b) ∨ q₂ = ((0 : G54), b) ∨
    q₃ = ((0 : G54), b) ∨
    ∃ h : G54, SmallCycle.termAt a108 b108 ((0 : G54), b) h
      + SmallCycle.termAt a108 b108 q₁ h
      + SmallCycle.termAt a108 b108 q₂ h
      + SmallCycle.termAt a108 b108 q₃ h ≠ 0 := by
  native_decide

/-- The small-cycle bundle: the four finite obligations, machine-checked. -/
def floorData : SmallCycleData G54 where
  A := a108
  B := b108
  epsA := epsA_holds
  epsB := epsB_holds
  check_two := check_two_holds
  check_four := check_four_holds

lemma floorData_complex : floorData.complex = bb108Complex := rfl

/-- **Strong small-cycle floor**: every nonzero 1-cycle of the bb_108
complex has weight ≥ 6 — boundaries included. -/
theorem strong_floor (u : G54 × Fin 2 → ZMod 2)
    (hcyc : bbBoundary1Fn a108 b108 u = 0) (hne : u ≠ 0) :
    6 ≤ (Finset.univ.filter fun p => u p ≠ 0).card :=
  floorData.cycle_weight_ge_6 u hcyc hne

/-- Chain-level d ≥ 6 on nontrivial cycles. -/
theorem chain_floor :
    ∀ u ∈ bb108Complex.cycles, u ∉ bb108Complex.boundaries →
      6 ≤ bb108Complex.chainWeight u :=
  floorData.chain_floor

/-- Dual-side chain floor (via the Φ duality). -/
theorem dual_chain_floor :
    ∀ c ∈ bb108Complex.dualCycles, c ∉ bb108Complex.dualBoundaries →
      6 ≤ bb108Complex.chainWeight c :=
  floorData.dual_chain_floor

/-- **Pauli-level logical floor**: every nontrivial logical operator of the
bb_108 homological stabilizer group has weight ≥ 6. -/
theorem logical_weight_ge_6
    (g : NQubitPauliGroupElement bb108Complex.numQubits)
    (hg : Quantum.StabilizerGroup.IsNontrivialLogicalOperator g
      bb108Complex.homologicalStabilizerGroup) :
    6 ≤ NQubitPauliGroupElement.weight g :=
  floorData.logical_weight_ge_6 g hg

/-- Nonzero stabilizer chains (images of `∂₂`) also weigh ≥ 6. -/
theorem stab_weight_ge_6 (f : G54 → ZMod 2)
    (hne : bbBoundary2Fn a108 b108 f ≠ 0) :
    6 ≤ (Finset.univ.filter
      fun p => bbBoundary2Fn a108 b108 f p ≠ 0).card :=
  floorData.stab_weight_ge_6 f hne

end BB108
end BB
end Homological
end Stabilizer
end Quantum
