/-
# Class base floor: bb_90 = [[90,8,10]] on `Z15 × Z3` — d ≥ 6 in strong form

Instance of the parametric small-cycle bundle
(`Framework/Homological/BBSmallCycle.lean`): every nonzero 1-cycle of the
bb_90 complex has weight ≥ 6.  Exported corollaries: the chain floor on
nontrivial cycles, the dual floor, the Pauli-level logical floor, and the
stabilizer-weight floor.

The code is a certified member of the class small-cycle theorem
(A16 write-up of record; certifier
`experiments/bb_lab/scripts/a15_class_certify.py`), so the four finite
obligations discharged below by `native_decide` are its engineering-grade
leaves.
True SAT distance d = 10; the class theorem certifies the analytic floor
6.

Polynomials (exponent pairs (x, y)): `A = x^9 + y + y^2`, `B = 1 + x^2 + x^7`.

Generated by `experiments/bb_lab/scripts/gen_base_floor_lean.py`; the
polynomial data is machine-written — regenerate rather than hand-edit.
-/

import QEC.Stabilizer.Framework.Homological.BBSmallCycle

namespace Quantum
namespace Stabilizer
namespace Homological
namespace BB
namespace BB90

/-- The group `Z15 × Z3`. -/
abbrev G45 : Type := ZMod 15 × ZMod 3

/-- `A = x^9 + y + y^2`. -/
def a90 : G45 → ZMod 2 := fun g =>
  if g = (0, 1) ∨ g = (0, 2) ∨ g = (9, 0) then 1 else 0

/-- `B = 1 + x^2 + x^7`. -/
def b90 : G45 → ZMod 2 := fun g =>
  if g = (0, 0) ∨ g = (2, 0) ∨ g = (7, 0) then 1 else 0

/-- The bb_90 chain complex. -/
noncomputable def bb90Complex : HomologicalCode := bbChainComplex a90 b90

theorem bb90Complex_numQubits : bb90Complex.numQubits = 90 := by
  change bbNumQubits G45 = 90
  unfold bbNumQubits
  rw [Fintype.card_prod, ZMod.card, ZMod.card]

/-! The four finite obligations, one declaration each (each `native_decide`
gets its own heartbeat budget — bundling them into the structure literal
blows the single-declaration limit on the larger groups). -/

/-- `ε(A) = 1`. -/
lemma epsA_holds : ∑ h : G45, a90 h = 1 := by native_decide

/-- `ε(B) = 1`. -/
lemma epsB_holds : ∑ h : G45, b90 h = 1 := by native_decide

/-- No normalized weight-2 cycle. -/
lemma check_two_holds : ∀ b : Fin 2, ∀ q : G45 × Fin 2,
    q ≠ ((0 : G45), b) →
    ∃ h : G45, SmallCycle.termAt a90 b90 ((0 : G45), b) h
      + SmallCycle.termAt a90 b90 q h ≠ 0 := by
  native_decide

/-- No normalized weight-4 cycle (tuple form; colliding tuples cancel to
the weight-2 shape). -/
lemma check_four_holds : ∀ b : Fin 2, ∀ q₁ q₂ q₃ : G45 × Fin 2,
    q₁ = ((0 : G45), b) ∨ q₂ = ((0 : G45), b) ∨
    q₃ = ((0 : G45), b) ∨
    ∃ h : G45, SmallCycle.termAt a90 b90 ((0 : G45), b) h
      + SmallCycle.termAt a90 b90 q₁ h
      + SmallCycle.termAt a90 b90 q₂ h
      + SmallCycle.termAt a90 b90 q₃ h ≠ 0 := by
  native_decide

/-- The small-cycle bundle: the four finite obligations, machine-checked. -/
def floorData : SmallCycleData G45 where
  A := a90
  B := b90
  epsA := epsA_holds
  epsB := epsB_holds
  check_two := check_two_holds
  check_four := check_four_holds

lemma floorData_complex : floorData.complex = bb90Complex := rfl

/-- **Strong small-cycle floor**: every nonzero 1-cycle of the bb_90
complex has weight ≥ 6 — boundaries included. -/
theorem strong_floor (u : G45 × Fin 2 → ZMod 2)
    (hcyc : bbBoundary1Fn a90 b90 u = 0) (hne : u ≠ 0) :
    6 ≤ (Finset.univ.filter fun p => u p ≠ 0).card :=
  floorData.cycle_weight_ge_6 u hcyc hne

/-- Chain-level d ≥ 6 on nontrivial cycles. -/
theorem chain_floor :
    ∀ u ∈ bb90Complex.cycles, u ∉ bb90Complex.boundaries →
      6 ≤ bb90Complex.chainWeight u :=
  floorData.chain_floor

/-- Dual-side chain floor (via the Φ duality). -/
theorem dual_chain_floor :
    ∀ c ∈ bb90Complex.dualCycles, c ∉ bb90Complex.dualBoundaries →
      6 ≤ bb90Complex.chainWeight c :=
  floorData.dual_chain_floor

/-- **Pauli-level logical floor**: every nontrivial logical operator of the
bb_90 homological stabilizer group has weight ≥ 6. -/
theorem logical_weight_ge_6
    (g : NQubitPauliGroupElement bb90Complex.numQubits)
    (hg : Quantum.StabilizerGroup.IsNontrivialLogicalOperator g
      bb90Complex.homologicalStabilizerGroup) :
    6 ≤ NQubitPauliGroupElement.weight g :=
  floorData.logical_weight_ge_6 g hg

/-- Nonzero stabilizer chains (images of `∂₂`) also weigh ≥ 6. -/
theorem stab_weight_ge_6 (f : G45 → ZMod 2)
    (hne : bbBoundary2Fn a90 b90 f ≠ 0) :
    6 ≤ (Finset.univ.filter
      fun p => bbBoundary2Fn a90 b90 f p ≠ 0).card :=
  floorData.stab_weight_ge_6 f hne

end BB90
end BB
end Homological
end Stabilizer
end Quantum
