/-
# Class base floor: bb_z6z14 = [[168,12,6]] on `Z6 × Z14` — d ≥ 6 in strong form

Instance of the parametric small-cycle bundle
(`Framework/Homological/BBSmallCycle.lean`): every nonzero 1-cycle of the
bb_z6z14 complex has weight ≥ 6.  Exported corollaries: the chain floor on
nontrivial cycles, the dual floor, the Pauli-level logical floor, and the
stabilizer-weight floor.

The code is a certified member of the class small-cycle theorem
(A16 write-up of record; certifier
`experiments/bb_lab/scripts/a15_class_certify.py`), so the four finite
obligations discharged below by `native_decide` are its engineering-grade
leaves.
SAT distance d = 6, so the floor is tight (first analytic member off the
Z3xZ3 odd-part family).

Polynomials (exponent pairs (x, y)): `A = 1 + y + x^3*y^3`, `B = 1 + x + x^2*y^7`.

Generated by `experiments/bb_lab/scripts/gen_base_floor_lean.py`; the
polynomial data is machine-written — regenerate rather than hand-edit.
-/

import QEC.Stabilizer.Framework.Homological.BBSmallCycle

namespace Quantum
namespace Stabilizer
namespace Homological
namespace BB
namespace Z6Z14

/-- The group `Z6 × Z14`. -/
abbrev G84 : Type := ZMod 6 × ZMod 14

/-- `A = 1 + y + x^3*y^3`. -/
def az6z14 : G84 → ZMod 2 := fun g =>
  if g = (0, 0) ∨ g = (0, 1) ∨ g = (3, 3) then 1 else 0

/-- `B = 1 + x + x^2*y^7`. -/
def bz6z14 : G84 → ZMod 2 := fun g =>
  if g = (0, 0) ∨ g = (1, 0) ∨ g = (2, 7) then 1 else 0

/-- The bb_z6z14 chain complex. -/
noncomputable def z6z14Complex : HomologicalCode := bbChainComplex az6z14 bz6z14

theorem z6z14Complex_numQubits : z6z14Complex.numQubits = 168 := by
  change bbNumQubits G84 = 168
  unfold bbNumQubits
  rw [Fintype.card_prod, ZMod.card, ZMod.card]

/-! The four finite obligations, one declaration each (each `native_decide`
gets its own heartbeat budget — bundling them into the structure literal
blows the single-declaration limit on the larger groups). -/

/-- `ε(A) = 1`. -/
lemma epsA_holds : ∑ h : G84, az6z14 h = 1 := by native_decide

/-- `ε(B) = 1`. -/
lemma epsB_holds : ∑ h : G84, bz6z14 h = 1 := by native_decide

/-- No normalized weight-2 cycle. -/
lemma check_two_holds : ∀ b : Fin 2, ∀ q : G84 × Fin 2,
    q ≠ ((0 : G84), b) →
    ∃ h : G84, SmallCycle.termAt az6z14 bz6z14 ((0 : G84), b) h
      + SmallCycle.termAt az6z14 bz6z14 q h ≠ 0 := by
  native_decide

/-- No normalized weight-4 cycle (tuple form; colliding tuples cancel to
the weight-2 shape). -/
lemma check_four_holds : ∀ b : Fin 2, ∀ q₁ q₂ q₃ : G84 × Fin 2,
    q₁ = ((0 : G84), b) ∨ q₂ = ((0 : G84), b) ∨
    q₃ = ((0 : G84), b) ∨
    ∃ h : G84, SmallCycle.termAt az6z14 bz6z14 ((0 : G84), b) h
      + SmallCycle.termAt az6z14 bz6z14 q₁ h
      + SmallCycle.termAt az6z14 bz6z14 q₂ h
      + SmallCycle.termAt az6z14 bz6z14 q₃ h ≠ 0 := by
  native_decide

/-- The small-cycle bundle: the four finite obligations, machine-checked. -/
def floorData : SmallCycleData G84 where
  A := az6z14
  B := bz6z14
  epsA := epsA_holds
  epsB := epsB_holds
  check_two := check_two_holds
  check_four := check_four_holds

lemma floorData_complex : floorData.complex = z6z14Complex := rfl

/-- **Strong small-cycle floor**: every nonzero 1-cycle of the bb_z6z14
complex has weight ≥ 6 — boundaries included. -/
theorem strong_floor (u : G84 × Fin 2 → ZMod 2)
    (hcyc : bbBoundary1Fn az6z14 bz6z14 u = 0) (hne : u ≠ 0) :
    6 ≤ (Finset.univ.filter fun p => u p ≠ 0).card :=
  floorData.cycle_weight_ge_6 u hcyc hne

/-- Chain-level d ≥ 6 on nontrivial cycles. -/
theorem chain_floor :
    ∀ u ∈ z6z14Complex.cycles, u ∉ z6z14Complex.boundaries →
      6 ≤ z6z14Complex.chainWeight u :=
  floorData.chain_floor

/-- Dual-side chain floor (via the Φ duality). -/
theorem dual_chain_floor :
    ∀ c ∈ z6z14Complex.dualCycles, c ∉ z6z14Complex.dualBoundaries →
      6 ≤ z6z14Complex.chainWeight c :=
  floorData.dual_chain_floor

/-- **Pauli-level logical floor**: every nontrivial logical operator of the
bb_z6z14 homological stabilizer group has weight ≥ 6. -/
theorem logical_weight_ge_6
    (g : NQubitPauliGroupElement z6z14Complex.numQubits)
    (hg : Quantum.StabilizerGroup.IsNontrivialLogicalOperator g
      z6z14Complex.homologicalStabilizerGroup) :
    6 ≤ NQubitPauliGroupElement.weight g :=
  floorData.logical_weight_ge_6 g hg

/-- Nonzero stabilizer chains (images of `∂₂`) also weigh ≥ 6. -/
theorem stab_weight_ge_6 (f : G84 → ZMod 2)
    (hne : bbBoundary2Fn az6z14 bz6z14 f ≠ 0) :
    6 ≤ (Finset.univ.filter
      fun p => bbBoundary2Fn az6z14 bz6z14 f p ≠ 0).card :=
  floorData.stab_weight_ge_6 f hne

end Z6Z14
end BB
end Homological
end Stabilizer
end Quantum
