/-
# Umbrella: class base floors (T2 layer)

Per-instance `SmallCycleData` bundles for certified members of the class
small-cycle theorem (A16).  Generated by
`experiments/bb_lab/scripts/gen_base_floor_lean.py`.
-/

import QEC.Stabilizer.Codes.BivariateBicycle.BaseFloors.BB108
import QEC.Stabilizer.Codes.BivariateBicycle.BaseFloors.BB90
import QEC.Stabilizer.Codes.BivariateBicycle.BaseFloors.Z6Z14
