/-
# Phase 6: assembling `MImBound` — the 2-D-orbit dispatch

`floor_kcombo` dispatches an arbitrary `ker ∂₂` class `kcombo c` over its 64 free-cell values:
the zero class is vacuous (`seamC 0 = 0`, so the coset is a boundary, contradicting the
hypothesis), and each of the 63 nonzero classes is a `(j,k)`-translate of one of the **5**
full-translation-orbit representatives (`MImFloorY0, Y1, Y4, Y11, Y12`), whose floor transports
via `floor_transfer` (`MImTransport §17`).  Pure `y`-shifts use a zero defect; the general
`x`-shift carries an explicit boundary defect `mkZeta …` (the §9.3 cut-shift, absorbed into the
re-indexed free chain).  `mimBound_holds` then reduces any `ζ ∈ ker ∂₂` to `kcombo` form
(`kerBasis_spans`) and applies the dispatch — discharging the last assumed `Prop` of the Gross
`[[144,12,12]]` distance proof.  The per-class shifts + boundary defects are generated by
`experiments/bb_lab/scripts/gen_assembly_2d.py` (the 2-D variant of `gen_assembly.py`).
-/
import QEC.Stabilizer.Codes.BivariateBicycle.MImTransport
import QEC.Stabilizer.Codes.BivariateBicycle.StabilizerCode
import QEC.Stabilizer.Codes.BivariateBicycle.MImFloorY0
import QEC.Stabilizer.Codes.BivariateBicycle.MImFloorY1
import QEC.Stabilizer.Codes.BivariateBicycle.MImFloorY4
import QEC.Stabilizer.Codes.BivariateBicycle.MImFloorY11
import QEC.Stabilizer.Codes.BivariateBicycle.MImFloorY12

open Quantum.Stabilizer.Homological.BB
open Quantum.Stabilizer.Homological.BB.LightStab

namespace Quantum.Stabilizer.Homological.BB.LightStab

set_option maxRecDepth 4096

/-- `seamC` is additive, so it kills `0`. -/
theorem seamC_zero : seamC 0 = 0 := by
  have h : seamC 0 + seamC 0 = seamC 0 + 0 := by rw [← seamC_add, add_zero, add_zero]
  exact add_left_cancel h

/-- The all-zero `kcombo` is the zero class. -/
theorem kcombo_zero : kcombo 0 0 0 0 0 0 = 0 := by funext h; simp [kcombo]

/-- The two values of `ZMod 2` (case-split with literal substitution). -/
theorem zmod2_cases (c : ZMod 2) : c = 0 ∨ c = 1 := by revert c; decide

/-- **The 2-D-orbit dispatch**: every `ker ∂₂` class, addressed by its six free-cell values, has
safe-sector floor `≥ 12` (the zero class is vacuous; the rest transport to one of the 5
full-orbit reps via `floor_transfer`). -/
theorem floor_kcombo (c0 c1 c2 c3 c4 c5 : ZMod 2) (f : BaseGroup → ZMod 2)
    (hb : seamC (kcombo c0 c1 c2 c3 c4 c5) + bbBoundary2Fn baseA baseB f
      ∉ bb72Complex.boundaries) :
    12 ≤ bb72Complex.chainWeight (seamC (kcombo c0 c1 c2 c3 c4 c5)
      + bbBoundary2Fn baseA baseB f) := by
  rcases zmod2_cases c0 with rfl | rfl <;> rcases zmod2_cases c1 with rfl | rfl <;>
    rcases zmod2_cases c2 with rfl | rfl <;> rcases zmod2_cases c3 with rfl | rfl <;>
    rcases zmod2_cases c4 with rfl | rfl <;> rcases zmod2_cases c5 with rfl | rfl
  · rw [kcombo_zero, seamC_zero, zero_add] at hb; exact absurd ⟨f, rfl⟩ hb
  · exact floor_transfer Y1.zrep (kcombo 0 0 0 0 0 1) ((1, 5) : BaseGroup)
      (mkZeta [(5,1),(5,5)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 0 0 0 1 0) ((1, 0) : BaseGroup)
      (mkZeta [(5,0),(5,4)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 0 0 0 1 1) ((4, 1) : BaseGroup)
      (mkZeta [(0,0),(0,1),(0,2),(0,5),(1,1),(1,5)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 0 0 1 0 0) ((2, 4) : BaseGroup)
      (mkZeta [(4,0),(4,2),(5,1),(5,3)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y4.zrep (kcombo 0 0 0 1 0 1) ((0, 3) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y4.floor f
  · exact floor_transfer Y0.zrep (kcombo 0 0 0 1 1 0) ((1, 0) : BaseGroup)
      (mkZeta [(5,0),(5,1),(5,3),(5,4)])
      (by native_decide) Y0.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 0 0 1 1 1) ((3, 4) : BaseGroup)
      (mkZeta [(3,0),(3,2),(4,1),(4,3),(5,0),(5,3),(5,4),(5,5)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 0 1 0 0 0) ((0, 0) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y4.zrep (kcombo 0 0 1 0 0 1) ((1, 0) : BaseGroup)
      (mkZeta [(5,0),(5,1),(5,2),(5,5)])
      (by native_decide) Y4.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 0 1 0 1 0) ((2, 3) : BaseGroup)
      (mkZeta [(4,1),(4,3),(5,2),(5,4)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y0.zrep (kcombo 0 0 1 0 1 1) ((1, 2) : BaseGroup)
      (mkZeta [(5,1),(5,2),(5,4),(5,5)])
      (by native_decide) Y0.floor f
  · exact floor_transfer Y4.zrep (kcombo 0 0 1 1 0 0) ((1, 5) : BaseGroup)
      (mkZeta [(5,0),(5,1),(5,2),(5,3)])
      (by native_decide) Y4.floor f
  · exact floor_transfer Y0.zrep (kcombo 0 0 1 1 0 1) ((1, 1) : BaseGroup)
      (mkZeta [(5,0),(5,2),(5,3),(5,5)])
      (by native_decide) Y0.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 0 1 1 1 0) ((5, 5) : BaseGroup)
      (mkZeta [(0,1),(0,3)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 0 1 1 1 1) ((3, 5) : BaseGroup)
      (mkZeta [(3,1),(3,5),(4,0),(4,2),(5,2),(5,3),(5,4),(5,5)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y0.zrep (kcombo 0 1 0 0 0 0) ((0, 1) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y0.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 1 0 0 0 1) ((0, 1) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 1 0 0 1 0) ((2, 1) : BaseGroup)
      (mkZeta [(4,3),(4,5),(5,0),(5,4)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y4.zrep (kcombo 0 1 0 0 1 1) ((1, 1) : BaseGroup)
      (mkZeta [(5,0),(5,1),(5,4),(5,5)])
      (by native_decide) Y4.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 1 0 1 0 0) ((1, 3) : BaseGroup)
      (mkZeta [(5,1),(5,3)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 1 0 1 0 1) ((1, 1) : BaseGroup)
      (mkZeta [(5,3),(5,5)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y11.zrep (kcombo 0 1 0 1 1 0) ((0, 0) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y11.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 1 0 1 1 1) ((4, 2) : BaseGroup)
      (mkZeta [(0,0),(0,1),(0,4),(0,5),(1,0),(1,4)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 1 1 0 0 0) ((2, 5) : BaseGroup)
      (mkZeta [(4,1),(4,5),(5,0),(5,2)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 1 1 0 0 1) ((3, 2) : BaseGroup)
      (mkZeta [(3,2),(3,4),(4,3),(4,5),(5,0),(5,1),(5,2),(5,5)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y4.zrep (kcombo 0 1 1 0 1 0) ((0, 4) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y4.floor f
  · exact floor_transfer Y12.zrep (kcombo 0 1 1 0 1 1) ((0, 2) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y12.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 1 1 1 0 0) ((5, 0) : BaseGroup)
      (mkZeta [(0,0),(0,2)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y0.zrep (kcombo 0 1 1 1 0 1) ((2, 1) : BaseGroup)
      (mkZeta [(1,0),(1,2),(1,3),(1,5),(2,0),(2,2),(2,3),(2,5)])
      (by native_decide) Y0.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 1 1 1 1 0) ((3, 0) : BaseGroup)
      (mkZeta [(3,0),(3,4),(4,1),(4,5),(5,1),(5,2),(5,3),(5,4)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y4.zrep (kcombo 0 1 1 1 1 1) ((1, 3) : BaseGroup)
      (mkZeta [(5,2),(5,3),(5,4),(5,5)])
      (by native_decide) Y4.floor f
  · exact floor_transfer Y0.zrep (kcombo 1 0 0 0 0 0) ((0, 0) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y0.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 0 0 0 0 1) ((2, 0) : BaseGroup)
      (mkZeta [(4,0),(4,4),(5,1),(5,5)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y4.zrep (kcombo 1 0 0 0 1 0) ((0, 2) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y4.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 0 0 0 1 1) ((3, 3) : BaseGroup)
      (mkZeta [(3,1),(3,3),(4,2),(4,4),(5,0),(5,1),(5,4),(5,5)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 0 0 1 0 0) ((0, 5) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 0 0 1 0 1) ((2, 2) : BaseGroup)
      (mkZeta [(4,2),(4,4),(5,3),(5,5)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y0.zrep (kcombo 1 0 0 1 1 0) ((2, 0) : BaseGroup)
      (mkZeta [(1,0),(1,1),(1,3),(1,4),(2,0),(2,1),(2,3),(2,4)])
      (by native_decide) Y0.floor f
  · exact floor_transfer Y4.zrep (kcombo 1 0 0 1 1 1) ((1, 2) : BaseGroup)
      (mkZeta [(5,0),(5,3),(5,4),(5,5)])
      (by native_decide) Y4.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 0 1 0 0 0) ((1, 4) : BaseGroup)
      (mkZeta [(5,0),(5,2)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 0 1 0 0 1) ((4, 0) : BaseGroup)
      (mkZeta [(0,0),(0,1),(0,2),(0,3),(1,0),(1,2)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 0 1 0 1 0) ((1, 2) : BaseGroup)
      (mkZeta [(5,2),(5,4)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y11.zrep (kcombo 1 0 1 0 1 1) ((0, 2) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y11.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 0 1 1 0 0) ((3, 1) : BaseGroup)
      (mkZeta [(3,3),(3,5),(4,0),(4,4),(5,0),(5,1),(5,2),(5,3)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y12.zrep (kcombo 1 0 1 1 0 1) ((0, 1) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y12.floor f
  · exact floor_transfer Y4.zrep (kcombo 1 0 1 1 1 0) ((1, 4) : BaseGroup)
      (mkZeta [(5,1),(5,2),(5,3),(5,4)])
      (by native_decide) Y4.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 0 1 1 1 1) ((5, 4) : BaseGroup)
      (mkZeta [(0,2),(0,4)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y0.zrep (kcombo 1 1 0 0 0 0) ((0, 2) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y0.floor f
  · exact floor_transfer Y4.zrep (kcombo 1 1 0 0 0 1) ((0, 1) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y4.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 1 0 0 1 0) ((0, 2) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 1 0 0 1 1) ((5, 2) : BaseGroup)
      (mkZeta [(0,0),(0,4)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y4.zrep (kcombo 1 1 0 1 0 0) ((0, 5) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y4.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 1 0 1 0 1) ((0, 3) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y12.zrep (kcombo 1 1 0 1 1 0) ((0, 0) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y12.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 1 0 1 1 1) ((5, 3) : BaseGroup)
      (mkZeta [(0,3),(0,5)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y4.zrep (kcombo 1 1 1 0 0 0) ((0, 0) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y4.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 1 1 0 0 1) ((5, 1) : BaseGroup)
      (mkZeta [(0,1),(0,5)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 1 1 0 1 0) ((0, 4) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y0.zrep (kcombo 1 1 1 0 1 1) ((2, 2) : BaseGroup)
      (mkZeta [(1,1),(1,2),(1,4),(1,5),(2,1),(2,2),(2,4),(2,5)])
      (by native_decide) Y0.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 1 1 1 0 0) ((4, 5) : BaseGroup)
      (mkZeta [(0,1),(0,2),(0,3),(0,4),(1,1),(1,3)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y11.zrep (kcombo 1 1 1 1 0 1) ((0, 1) : BaseGroup)
      (mkZeta [])
      (by native_decide) Y11.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 1 1 1 1 0) ((4, 4) : BaseGroup)
      (mkZeta [(0,2),(0,3),(0,4),(0,5),(1,2),(1,4)])
      (by native_decide) Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 1 1 1 1 1) ((4, 3) : BaseGroup)
      (mkZeta [(0,0),(0,3),(0,4),(0,5),(1,3),(1,5)])
      (by native_decide) Y1.floor f

/-- **`MImBound` holds** — the last assumed `Prop` for unconditional `d(gross) = 12`. -/
theorem mimBound_holds : MImBound := by
  intro ζ hζ f hb
  have h : ζ = kcombo (ζ (4,4)) (ζ (4,5)) (ζ (5,2)) (ζ (5,3)) (ζ (5,4)) (ζ (5,5)) :=
    (kerBasis_spans ζ hζ).symm.trans (recon_eq_kcombo ζ)
  rw [h] at hb ⊢
  exact floor_kcombo (ζ (4,4)) (ζ (4,5)) (ζ (5,2)) (ζ (5,3)) (ζ (5,4)) (ζ (5,5)) f hb

end Quantum.Stabilizer.Homological.BB.LightStab

namespace Quantum.Stabilizer.Homological.BB

/-- **Unconditional `HasCodeDistance grossStabilizerCode 12`** — the Gross `[[144,12,12]]`
bivariate-bicycle code has distance exactly 12, with NO remaining assumed hypotheses.  The
last analytic input `MImBound` is discharged by `LightStab.mimBound_holds`; the
`LightStabilizerClassification` input was discharged earlier by
`LightStab.lightStabilizerClassification_holds`.  Axiom-clean (the standard three + the
`native_decide` compiler axiom). -/
theorem grossStabilizerCode_hasCodeDistance_12_uncond :
    Quantum.StabilizerGroup.HasCodeDistance grossStabilizerCode 12 :=
  grossStabilizerCode_hasCodeDistance_12 LightStab.mimBound_holds

/-- **The Gross `[[144, 12, 12]]` code as a fully-parametrized object.**  Bundles the
stabilizer code (`StabilizerCode 144 12`) with its now-unconditional distance proof into a
single `StabilizerCodeWithDistance` carrying all three `[[n, k, d]]` parameters in its type. -/
noncomputable def grossStabilizerCodeWithDistance :
    Quantum.StabilizerGroup.StabilizerCodeWithDistance 144 12 12 where
  toStabilizerCode := grossStabilizerCode
  hasDistance := grossStabilizerCode_hasCodeDistance_12_uncond

end Quantum.Stabilizer.Homological.BB
