/-
# Phase 6: assembling `MImBound` — the y-orbit dispatch

`floor_kcombo` dispatches an arbitrary `ker ∂₂` class `kcombo c` over its 64 free-cell values:
the zero class is vacuous (`seamC 0 = 0`, so the coset is a boundary, contradicting the
hypothesis), and each of the 63 nonzero classes is a `(0,k)`-translate of one of the 13 y-orbit
representatives (`MImFloorY0`..`MImFloorY12`), whose floor transports via `floor_shiftYk_combo`
(`MImTransport §16`).  `mimBound_holds` then reduces any `ζ ∈ ker ∂₂` to `kcombo` form
(`kerBasis_spans`) and applies the dispatch — discharging the last assumed `Prop` of the
Gross `[[144,12,12]]` distance proof.  Generated by `experiments/bb_lab/scripts/gen_assembly.py`.
-/
import QEC.Stabilizer.Codes.BivariateBicycle.MImTransport
import QEC.Stabilizer.Codes.BivariateBicycle.StabilizerCode
import QEC.Stabilizer.Codes.BivariateBicycle.MImFloorY0
import QEC.Stabilizer.Codes.BivariateBicycle.MImFloorY1
import QEC.Stabilizer.Codes.BivariateBicycle.MImFloorY2
import QEC.Stabilizer.Codes.BivariateBicycle.MImFloorY3
import QEC.Stabilizer.Codes.BivariateBicycle.MImFloorY4
import QEC.Stabilizer.Codes.BivariateBicycle.MImFloorY5
import QEC.Stabilizer.Codes.BivariateBicycle.MImFloorY6
import QEC.Stabilizer.Codes.BivariateBicycle.MImFloorY7
import QEC.Stabilizer.Codes.BivariateBicycle.MImFloorY8
import QEC.Stabilizer.Codes.BivariateBicycle.MImFloorY9
import QEC.Stabilizer.Codes.BivariateBicycle.MImFloorY10
import QEC.Stabilizer.Codes.BivariateBicycle.MImFloorY11
import QEC.Stabilizer.Codes.BivariateBicycle.MImFloorY12

open Quantum.Stabilizer.Homological.BB
open Quantum.Stabilizer.Homological.BB.LightStab

namespace Quantum.Stabilizer.Homological.BB.LightStab

set_option maxRecDepth 4096

/-- `seamC` is additive, so it kills `0`. -/
theorem seamC_zero : seamC 0 = 0 := by
  have h : seamC 0 + seamC 0 = seamC 0 + 0 := by rw [← seamC_add, add_zero, add_zero]
  exact add_left_cancel h

/-- The all-zero `kcombo` is the zero class. -/
theorem kcombo_zero : kcombo 0 0 0 0 0 0 = 0 := by funext h; simp [kcombo]

/-- The two values of `ZMod 2` (case-split with literal substitution). -/
theorem zmod2_cases (c : ZMod 2) : c = 0 ∨ c = 1 := by revert c; decide

/-- **The y-orbit dispatch**: every `ker ∂₂` class, addressed by its six free-cell values, has
safe-sector floor `≥ 12` (the zero class is vacuous; the rest transport to a y-orbit rep). -/
theorem floor_kcombo (c0 c1 c2 c3 c4 c5 : ZMod 2) (f : BaseGroup → ZMod 2)
    (hb : seamC (kcombo c0 c1 c2 c3 c4 c5) + bbBoundary2Fn baseA baseB f
      ∉ bb72Complex.boundaries) :
    12 ≤ bb72Complex.chainWeight (seamC (kcombo c0 c1 c2 c3 c4 c5)
      + bbBoundary2Fn baseA baseB f) := by
  rcases zmod2_cases c0 with rfl | rfl <;> rcases zmod2_cases c1 with rfl | rfl <;>
    rcases zmod2_cases c2 with rfl | rfl <;> rcases zmod2_cases c3 with rfl | rfl <;>
    rcases zmod2_cases c4 with rfl | rfl <;> rcases zmod2_cases c5 with rfl | rfl
  · rw [kcombo_zero, seamC_zero, zero_add] at hb; exact absurd ⟨f, rfl⟩ hb
  · rw [show kcombo 0 0 0 0 0 1 =
        translate ((0, 1) : BaseGroup) (kcombo 1 0 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 0 1 0 0 0 (1 : ZMod 6) Y2.floor f
  · rw [show kcombo 0 0 0 0 1 0 =
        translate ((0, 2) : BaseGroup) (kcombo 1 0 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 0 1 0 0 0 (2 : ZMod 6) Y2.floor f
  · rw [show kcombo 0 0 0 0 1 1 =
        translate ((0, 2) : BaseGroup) (kcombo 1 1 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 1 1 1 0 0 (2 : ZMod 6) Y8.floor f
  · rw [show kcombo 0 0 0 1 0 0 =
        translate ((0, 5) : BaseGroup) (kcombo 0 1 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 1 1 0 0 0 (5 : ZMod 6) Y3.floor f
  · rw [show kcombo 0 0 0 1 0 1 =
        translate ((0, 3) : BaseGroup) (kcombo 1 1 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 1 1 0 0 0 (3 : ZMod 6) Y4.floor f
  · rw [show kcombo 0 0 0 1 1 0 =
        translate ((0, 0) : BaseGroup) (kcombo 0 0 0 1 1 0) from by native_decide]
    exact floor_shiftYk_combo 0 0 0 1 1 0 (0 : ZMod 6) Y9.floor f
  · rw [show kcombo 0 0 0 1 1 1 =
        translate ((0, 3) : BaseGroup) (kcombo 1 0 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 0 1 1 0 0 (3 : ZMod 6) Y6.floor f
  · rw [show kcombo 0 0 1 0 0 0 =
        translate ((0, 0) : BaseGroup) (kcombo 0 0 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 0 1 0 0 0 (0 : ZMod 6) Y1.floor f
  · rw [show kcombo 0 0 1 0 0 1 =
        translate ((0, 1) : BaseGroup) (kcombo 0 0 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 0 1 1 0 0 (1 : ZMod 6) Y5.floor f
  · rw [show kcombo 0 0 1 0 1 0 =
        translate ((0, 4) : BaseGroup) (kcombo 0 1 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 1 1 0 0 0 (4 : ZMod 6) Y3.floor f
  · rw [show kcombo 0 0 1 0 1 1 =
        translate ((0, 2) : BaseGroup) (kcombo 0 0 0 1 1 0) from by native_decide]
    exact floor_shiftYk_combo 0 0 0 1 1 0 (2 : ZMod 6) Y9.floor f
  · rw [show kcombo 0 0 1 1 0 0 =
        translate ((0, 0) : BaseGroup) (kcombo 0 0 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 0 1 1 0 0 (0 : ZMod 6) Y5.floor f
  · rw [show kcombo 0 0 1 1 0 1 =
        translate ((0, 1) : BaseGroup) (kcombo 0 0 0 1 1 0) from by native_decide]
    exact floor_shiftYk_combo 0 0 0 1 1 0 (1 : ZMod 6) Y9.floor f
  · rw [show kcombo 0 0 1 1 1 0 =
        translate ((0, 5) : BaseGroup) (kcombo 0 1 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 1 1 1 0 0 (5 : ZMod 6) Y7.floor f
  · rw [show kcombo 0 0 1 1 1 1 =
        translate ((0, 4) : BaseGroup) (kcombo 1 0 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 0 1 1 0 0 (4 : ZMod 6) Y6.floor f
  · rw [show kcombo 0 1 0 0 0 0 =
        translate ((0, 1) : BaseGroup) (kcombo 1 0 0 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 0 0 0 0 0 (1 : ZMod 6) Y0.floor f
  · rw [show kcombo 0 1 0 0 0 1 =
        translate ((0, 1) : BaseGroup) (kcombo 0 0 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 0 1 0 0 0 (1 : ZMod 6) Y1.floor f
  · rw [show kcombo 0 1 0 0 1 0 =
        translate ((0, 2) : BaseGroup) (kcombo 0 1 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 1 1 0 0 0 (2 : ZMod 6) Y3.floor f
  · rw [show kcombo 0 1 0 0 1 1 =
        translate ((0, 2) : BaseGroup) (kcombo 0 0 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 0 1 1 0 0 (2 : ZMod 6) Y5.floor f
  · rw [show kcombo 0 1 0 1 0 0 =
        translate ((0, 5) : BaseGroup) (kcombo 1 0 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 0 1 0 0 0 (5 : ZMod 6) Y2.floor f
  · rw [show kcombo 0 1 0 1 0 1 =
        translate ((0, 3) : BaseGroup) (kcombo 1 0 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 0 1 0 0 0 (3 : ZMod 6) Y2.floor f
  · rw [show kcombo 0 1 0 1 1 0 =
        translate ((0, 0) : BaseGroup) (kcombo 0 1 0 1 1 0) from by native_decide]
    exact floor_shiftYk_combo 0 1 0 1 1 0 (0 : ZMod 6) Y11.floor f
  · rw [show kcombo 0 1 0 1 1 1 =
        translate ((0, 3) : BaseGroup) (kcombo 1 1 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 1 1 1 0 0 (3 : ZMod 6) Y8.floor f
  · rw [show kcombo 0 1 1 0 0 0 =
        translate ((0, 0) : BaseGroup) (kcombo 0 1 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 1 1 0 0 0 (0 : ZMod 6) Y3.floor f
  · rw [show kcombo 0 1 1 0 0 1 =
        translate ((0, 1) : BaseGroup) (kcombo 1 0 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 0 1 1 0 0 (1 : ZMod 6) Y6.floor f
  · rw [show kcombo 0 1 1 0 1 0 =
        translate ((0, 4) : BaseGroup) (kcombo 1 1 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 1 1 0 0 0 (4 : ZMod 6) Y4.floor f
  · rw [show kcombo 0 1 1 0 1 1 =
        translate ((0, 2) : BaseGroup) (kcombo 1 1 0 1 1 0) from by native_decide]
    exact floor_shiftYk_combo 1 1 0 1 1 0 (2 : ZMod 6) Y12.floor f
  · rw [show kcombo 0 1 1 1 0 0 =
        translate ((0, 0) : BaseGroup) (kcombo 0 1 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 1 1 1 0 0 (0 : ZMod 6) Y7.floor f
  · rw [show kcombo 0 1 1 1 0 1 =
        translate ((0, 1) : BaseGroup) (kcombo 1 0 0 1 1 0) from by native_decide]
    exact floor_shiftYk_combo 1 0 0 1 1 0 (1 : ZMod 6) Y10.floor f
  · rw [show kcombo 0 1 1 1 1 0 =
        translate ((0, 5) : BaseGroup) (kcombo 1 0 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 0 1 1 0 0 (5 : ZMod 6) Y6.floor f
  · rw [show kcombo 0 1 1 1 1 1 =
        translate ((0, 4) : BaseGroup) (kcombo 0 0 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 0 1 1 0 0 (4 : ZMod 6) Y5.floor f
  · rw [show kcombo 1 0 0 0 0 0 =
        translate ((0, 0) : BaseGroup) (kcombo 1 0 0 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 0 0 0 0 0 (0 : ZMod 6) Y0.floor f
  · rw [show kcombo 1 0 0 0 0 1 =
        translate ((0, 1) : BaseGroup) (kcombo 0 1 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 1 1 0 0 0 (1 : ZMod 6) Y3.floor f
  · rw [show kcombo 1 0 0 0 1 0 =
        translate ((0, 2) : BaseGroup) (kcombo 1 1 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 1 1 0 0 0 (2 : ZMod 6) Y4.floor f
  · rw [show kcombo 1 0 0 0 1 1 =
        translate ((0, 2) : BaseGroup) (kcombo 1 0 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 0 1 1 0 0 (2 : ZMod 6) Y6.floor f
  · rw [show kcombo 1 0 0 1 0 0 =
        translate ((0, 5) : BaseGroup) (kcombo 0 0 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 0 1 0 0 0 (5 : ZMod 6) Y1.floor f
  · rw [show kcombo 1 0 0 1 0 1 =
        translate ((0, 3) : BaseGroup) (kcombo 0 1 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 1 1 0 0 0 (3 : ZMod 6) Y3.floor f
  · rw [show kcombo 1 0 0 1 1 0 =
        translate ((0, 0) : BaseGroup) (kcombo 1 0 0 1 1 0) from by native_decide]
    exact floor_shiftYk_combo 1 0 0 1 1 0 (0 : ZMod 6) Y10.floor f
  · rw [show kcombo 1 0 0 1 1 1 =
        translate ((0, 3) : BaseGroup) (kcombo 0 0 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 0 1 1 0 0 (3 : ZMod 6) Y5.floor f
  · rw [show kcombo 1 0 1 0 0 0 =
        translate ((0, 0) : BaseGroup) (kcombo 1 0 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 0 1 0 0 0 (0 : ZMod 6) Y2.floor f
  · rw [show kcombo 1 0 1 0 0 1 =
        translate ((0, 1) : BaseGroup) (kcombo 1 1 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 1 1 1 0 0 (1 : ZMod 6) Y8.floor f
  · rw [show kcombo 1 0 1 0 1 0 =
        translate ((0, 4) : BaseGroup) (kcombo 1 0 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 0 1 0 0 0 (4 : ZMod 6) Y2.floor f
  · rw [show kcombo 1 0 1 0 1 1 =
        translate ((0, 2) : BaseGroup) (kcombo 0 1 0 1 1 0) from by native_decide]
    exact floor_shiftYk_combo 0 1 0 1 1 0 (2 : ZMod 6) Y11.floor f
  · rw [show kcombo 1 0 1 1 0 0 =
        translate ((0, 0) : BaseGroup) (kcombo 1 0 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 0 1 1 0 0 (0 : ZMod 6) Y6.floor f
  · rw [show kcombo 1 0 1 1 0 1 =
        translate ((0, 1) : BaseGroup) (kcombo 1 1 0 1 1 0) from by native_decide]
    exact floor_shiftYk_combo 1 1 0 1 1 0 (1 : ZMod 6) Y12.floor f
  · rw [show kcombo 1 0 1 1 1 0 =
        translate ((0, 5) : BaseGroup) (kcombo 0 0 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 0 1 1 0 0 (5 : ZMod 6) Y5.floor f
  · rw [show kcombo 1 0 1 1 1 1 =
        translate ((0, 4) : BaseGroup) (kcombo 0 1 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 1 1 1 0 0 (4 : ZMod 6) Y7.floor f
  · rw [show kcombo 1 1 0 0 0 0 =
        translate ((0, 2) : BaseGroup) (kcombo 1 0 0 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 0 0 0 0 0 (2 : ZMod 6) Y0.floor f
  · rw [show kcombo 1 1 0 0 0 1 =
        translate ((0, 1) : BaseGroup) (kcombo 1 1 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 1 1 0 0 0 (1 : ZMod 6) Y4.floor f
  · rw [show kcombo 1 1 0 0 1 0 =
        translate ((0, 2) : BaseGroup) (kcombo 0 0 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 0 1 0 0 0 (2 : ZMod 6) Y1.floor f
  · rw [show kcombo 1 1 0 0 1 1 =
        translate ((0, 2) : BaseGroup) (kcombo 0 1 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 1 1 1 0 0 (2 : ZMod 6) Y7.floor f
  · rw [show kcombo 1 1 0 1 0 0 =
        translate ((0, 5) : BaseGroup) (kcombo 1 1 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 1 1 0 0 0 (5 : ZMod 6) Y4.floor f
  · rw [show kcombo 1 1 0 1 0 1 =
        translate ((0, 3) : BaseGroup) (kcombo 0 0 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 0 1 0 0 0 (3 : ZMod 6) Y1.floor f
  · rw [show kcombo 1 1 0 1 1 0 =
        translate ((0, 0) : BaseGroup) (kcombo 1 1 0 1 1 0) from by native_decide]
    exact floor_shiftYk_combo 1 1 0 1 1 0 (0 : ZMod 6) Y12.floor f
  · rw [show kcombo 1 1 0 1 1 1 =
        translate ((0, 3) : BaseGroup) (kcombo 0 1 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 1 1 1 0 0 (3 : ZMod 6) Y7.floor f
  · rw [show kcombo 1 1 1 0 0 0 =
        translate ((0, 0) : BaseGroup) (kcombo 1 1 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 1 1 0 0 0 (0 : ZMod 6) Y4.floor f
  · rw [show kcombo 1 1 1 0 0 1 =
        translate ((0, 1) : BaseGroup) (kcombo 0 1 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 1 1 1 0 0 (1 : ZMod 6) Y7.floor f
  · rw [show kcombo 1 1 1 0 1 0 =
        translate ((0, 4) : BaseGroup) (kcombo 0 0 1 0 0 0) from by native_decide]
    exact floor_shiftYk_combo 0 0 1 0 0 0 (4 : ZMod 6) Y1.floor f
  · rw [show kcombo 1 1 1 0 1 1 =
        translate ((0, 2) : BaseGroup) (kcombo 1 0 0 1 1 0) from by native_decide]
    exact floor_shiftYk_combo 1 0 0 1 1 0 (2 : ZMod 6) Y10.floor f
  · rw [show kcombo 1 1 1 1 0 0 =
        translate ((0, 0) : BaseGroup) (kcombo 1 1 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 1 1 1 0 0 (0 : ZMod 6) Y8.floor f
  · rw [show kcombo 1 1 1 1 0 1 =
        translate ((0, 1) : BaseGroup) (kcombo 0 1 0 1 1 0) from by native_decide]
    exact floor_shiftYk_combo 0 1 0 1 1 0 (1 : ZMod 6) Y11.floor f
  · rw [show kcombo 1 1 1 1 1 0 =
        translate ((0, 5) : BaseGroup) (kcombo 1 1 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 1 1 1 0 0 (5 : ZMod 6) Y8.floor f
  · rw [show kcombo 1 1 1 1 1 1 =
        translate ((0, 4) : BaseGroup) (kcombo 1 1 1 1 0 0) from by native_decide]
    exact floor_shiftYk_combo 1 1 1 1 0 0 (4 : ZMod 6) Y8.floor f

/-- **`MImBound` holds** — the last assumed `Prop` for unconditional `d(gross) = 12`. -/
theorem mimBound_holds : MImBound := by
  intro ζ hζ f hb
  have h : ζ = kcombo (ζ (4,4)) (ζ (4,5)) (ζ (5,2)) (ζ (5,3)) (ζ (5,4)) (ζ (5,5)) :=
    (kerBasis_spans ζ hζ).symm.trans (recon_eq_kcombo ζ)
  rw [h] at hb ⊢
  exact floor_kcombo (ζ (4,4)) (ζ (4,5)) (ζ (5,2)) (ζ (5,3)) (ζ (5,4)) (ζ (5,5)) f hb

end Quantum.Stabilizer.Homological.BB.LightStab

namespace Quantum.Stabilizer.Homological.BB

/-- **Unconditional `HasCodeDistance grossStabilizerCode 12`** — the Gross `[[144,12,12]]`
bivariate-bicycle code has distance exactly 12, with NO remaining assumed hypotheses.  The
last analytic input `MImBound` is discharged by `LightStab.mimBound_holds`; the
`LightStabilizerClassification` input was discharged earlier by
`LightStab.lightStabilizerClassification_holds`.  Axiom-clean (the standard three + the
`native_decide` compiler axiom). -/
theorem grossStabilizerCode_hasCodeDistance_12_uncond :
    Quantum.StabilizerGroup.HasCodeDistance grossStabilizerCode 12 :=
  grossStabilizerCode_hasCodeDistance_12 LightStab.mimBound_holds

end Quantum.Stabilizer.Homological.BB
