/-
# Phase 6: the weight-24 standard-form walk (A4 §11) — M1a

The slot-frame substrate (`SlotFrame.lean`, §10) is here specialized to the
**standard form** `S(a,b)` (Def 26) and the **standard-form walk** (Prop 29):
`S(a,b) ≥ 6` for all `(a,b) ∈ F₄²`, hence every weight-24 spine cell has linked
block cost `≥ 6 + 6 = 12`.  This is the §11 combinatorial core of the wt-24 floor.

Everything here is **axiom-clean** (kernel `decide`, standard three axioms only —
no `native_decide`/`ofReduceBool`):

* `slotCost v2 v3 v4` — the per-slot cost (Lemma 20), as the exact minimum over
  the free `v₀` (trivial-character, `F₂`) and `v₁` (free unit-side) of the layer
  weight `wt5OfComps`.  Tabled (`SLOTCOST`, 64 entries) for kernel-`decide` speed.
* `slotCost_le` — soundness: `slotCost` lower-bounds the exact per-slot weight
  `wt5OfComps` for every `v₀ ∈ F₂`, `v₁ ∈ F₄` (kernel `decide`, 512 tuples).
* `Sab a b` — the standard form (Def 26): the `v₀`-free block cost with confined
  line `⟨ℓ⟩`, component-3 direction `a·ℓ + c₃`, component-4 direction
  `b·ℓ + ωθ + c₄`, minimized over the free constants `p, c₂, c₃, c₄ ∈ F₄`.
* `Sab_ge_6` — **Proposition 29**: `S(a,b) ≥ 6` for all 16 pairs (kernel `decide`,
  the 256-knob × 4-slot × 16-pair walk; needs a `maxHeartbeats` bump, ~3 min).

The slot order is `allS = (e,x,y,xy) = (0,0),(1,0),(0,1),(1,1)`; over it the
labeling `ℓ = ellL = Bhat2 = (ω²,ω,1,0) = (3,2,1,0)` (a bijection, `ellL_inj`) and
`ωθ = ω·theta = (2,0,2,0)`; F₄ is `Fin 4` with `(0,1,ω,ω²)=(0,1,2,3)`.

The block-cost reduction (Lemma 27: `L(24a)=S(a₃,a₄)`, `R(24a)≅S(a₃,a₄²)`, …)
and the bridge to the actual coset weight `chainWeight (seamC zrep + ∂₂ f)`
(via `costFromComps`/`exCost`) are M1b, downstream of this file.
-/

import QEC.Stabilizer.Codes.BivariateBicycle.SlotFrame

open Quantum.Stabilizer.Homological.BB
open Quantum.Stabilizer.Homological.BB.CRTFrame
open Quantum.Stabilizer.Homological.BB.LightStab

namespace Quantum.Stabilizer.Homological.BB.LightStab

set_option maxRecDepth 8192

/-! ## §11.1 The per-slot cost `slotCost` (Lemma 20) and its soundness

`slotCost v2 v3 v4` is the exact minimum layer weight realizing the constrained
slot datum `(v2, v3, v4)` (the confined `v₂` and the spine `v₃, v₄`), minimized
over the free `v₀ ∈ {0,1}` (`F₂`-valued trivial character) and the free unit-side
`v₁ ∈ F₄`.  We pin it as a 64-entry table for kernel-`decide` speed; `slotCost_le`
certifies it is a genuine lower bound on `wt5OfComps`. -/

/-- The per-slot cost table (`v₂*16 + v₃*4 + v₄`), `= min_{v₀∈F₂, v₁∈F₄} wt5OfComps`.
Generated by `#eval` of that minimum over `SlotFrame`/`MImClassify.wt5OfComps`. -/
def SLOTCOST : Array Nat :=
  #[0,3,3,3,3,2,2,2,3,2,2,2,3,2,2,2,3,2,2,2,2,1,3,3,2,3,3,1,2,3,1,3,
    3,2,2,2,2,3,3,1,2,3,1,3,2,1,3,3,3,2,2,2,2,3,1,3,2,1,3,3,2,3,3,1]

/-- The per-slot cost (Lemma 20): the minimum layer weight for a slot datum
`(v₂, v₃, v₄)`, with the free `v₀`/`v₁` minimized out. -/
def slotCost (v2 v3 v4 : Fin 4) : Nat := SLOTCOST.getD (v2.val * 16 + v3.val * 4 + v4.val) 99

/-- **Slot-cost soundness (Lemma 20).** `slotCost` lower-bounds the exact per-slot
layer weight `wt5OfComps` for every free `v₀ ∈ F₂` and `v₁ ∈ F₄`.  Kernel `decide`
over the 512 value-tuples — **axiom-clean** (no `native_decide`). -/
theorem slotCost_le : ∀ (v0 : Fin 2) (v1 v2 v3 v4 : Fin 4),
    slotCost v2 v3 v4 ≤ wt5OfComps (v0.castLE (by norm_num)) v1 v2 v3 v4 := by decide

/-! ## §11.2 The standard form `S(a,b)` (Def 26) and the walk (Prop 29)

`S(a,b)` is the `v₀`-free block cost in standard form: over the four slots
`s` (where `ℓ(s)` ranges over all of `F₄`, as `ℓ` is a bijection), the confined
`v₂ = p·ℓ + c₂`, the spine `v₃ = a·ℓ + c₃`, `v₄ = b·ℓ + ωθ + c₄`, summed via
`slotCost` and minimized over the free `p, c₂, c₃, c₄ ∈ F₄`. -/

/-- The labeling `ℓ` over the four slots `(e,x,y,xy)`: `ℓ = (ω²,ω,1,0) = (3,2,1,0)`
(`= ellL`, by `ellL_eq`; `ellL_inj` is the bijectivity used in the pencil lemmas). -/
def ellSlots : List (Fin 4) := [3, 2, 1, 0]

/-- `ωθ` over the four slots: `ω·(1,0,1,0) = (2,0,2,0)` (the wt-24 component-4 offset). -/
def wThetaSlots : List (Fin 4) := [2, 0, 2, 0]

/-- `ellSlots` is genuinely `ℓ = ellL` evaluated over `allS = (e,x,y,xy)`. -/
theorem ellSlots_eq : ellSlots = [ellL (0,0), ellL (1,0), ellL (0,1), ellL (1,1)] := by decide

/-- `wThetaSlots` is genuinely `ωθ = ω·theta` evaluated over `allS`. -/
theorem wThetaSlots_eq :
    wThetaSlots = [fmul 2 (theta (0,0)), fmul 2 (theta (1,0)),
                   fmul 2 (theta (0,1)), fmul 2 (theta (1,1))] := by decide

/-- **The standard form `S(a,b)`** (Def 26): the `v₀`-free block cost with confined
line `⟨ℓ⟩`, spine directions `v₃ = a·ℓ + c₃`, `v₄ = b·ℓ + ωθ + c₄`, minimized over
the free constants `p, c₂, c₃, c₄ ∈ F₄`. -/
def Sab (a b : Fin 4) : Nat :=
  (([0,1,2,3] : List (Fin 4)).flatMap fun p => ([0,1,2,3] : List (Fin 4)).flatMap fun c2 =>
   ([0,1,2,3] : List (Fin 4)).flatMap fun c3 => ([0,1,2,3] : List (Fin 4)).map fun c4 =>
    (List.zip ellSlots wThetaSlots).foldr (fun pr acc =>
      acc + slotCost (fadd (fmul p pr.1) c2) (fadd (fmul a pr.1) c3)
                     (fadd (fadd (fmul b pr.1) pr.2) c4)) 0
  ).foldr min 999

set_option maxHeartbeats 4000000 in
-- The 16-pair × 256-knob × 4-slot standard-form walk is a large kernel `decide`
-- (~3 min); the bump keeps it kernel-checked (axiom-clean) rather than native_decide.
/-- **Proposition 29** (the standard-form walk): `S(a,b) ≥ 6` for all `(a,b) ∈ F₄²`.
Hence every weight-24 spine cell has linked block cost `≥ 6 + 6 = 12`.  Kernel
`decide` over the 16 pairs — **axiom-clean** (`propext` only). -/
theorem Sab_ge_6 : ∀ a b : Fin 4, 6 ≤ Sab a b := by decide

end Quantum.Stabilizer.Homological.BB.LightStab
