import Mathlib.Tactic
import QEC.Stabilizer.Framework.Core.Stabilizer.StabilizerGroup
import QEC.Stabilizer.Framework.Core.Stabilizer.SubgroupLemmas
import QEC.Stabilizer.Framework.Core.Stabilizer.Centralizer
import QEC.Stabilizer.Framework.Core.Logical.CodeDistance
import QEC.Stabilizer.Framework.Core.CSS.CSSDistance
import QEC.Stabilizer.Framework.Core.Logical.LogicalOperators
import QEC.Stabilizer.Framework.Core.Stabilizer.StabilizerCode
import QEC.Stabilizer.Framework.Symplectic.SymplecticSpan
import QEC.Stabilizer.Foundations.PauliGroup.Commutation
import QEC.Stabilizer.Foundations.PauliGroup.CommutationTactics
import QEC.Stabilizer.Foundations.PauliGroup.NQubitOperator
import QEC.Stabilizer.Foundations.PauliGroup.NQubitElement
import QEC.Stabilizer.Foundations.BinarySymplectic.Core
import QEC.Stabilizer.Foundations.BinarySymplectic.CheckMatrix
import QEC.Stabilizer.Foundations.BinarySymplectic.CheckMatrixDecidable
import QEC.Stabilizer.Framework.Symplectic.IndependentEquiv

namespace Quantum
open scoped BigOperators
open scoped Pauli

namespace StabilizerGroup
namespace FourQubit_4_2_2

/-!
# The [[4, 2, 2]] four-qubit code (also known as `C₄` or "Little Shor code")

A four-qubit hyperbolic self-dual CSS detection code with **two logical qubits**
and distance 2. Originally introduced in [Vaidman–Goldenberg–Wiesner 1996,
`arxiv:quant-ph/9603031`] and [Grassl–Beth–Pellizzari 1996,
`arxiv:quant-ph/9610042`].

The stabilizer is generated by two operators: `XXXX` and `ZZZZ`. The four
codeword basis states are
```
|0̄0̄⟩ = (|0000⟩ + |1111⟩)/√2
|0̄1̄⟩ = (|0011⟩ + |1100⟩)/√2
|1̄0̄⟩ = (|0101⟩ + |1010⟩)/√2
|1̄1̄⟩ = (|0110⟩ + |1001⟩)/√2
```
giving logical operators
```
X̄₁ = IXIX,  X̄₂ = IIXX,  Z̄₁ = IIZZ,  Z̄₂ = IZIZ.
```

The code is packaged by the **decide route**: the two generators form a literal
list, and pairwise commutation, phase zero and check-matrix independence are
closed statements settled by `decide`; `−I ∉ closure` follows by
`negIdentity_not_mem_of_indep_phase_zero_commute`.

## Outline

- Generators `Z1`, `X1` and the list `generatorsList`
- Decided hypotheses, `negIdentity_not_mem`, the bundled `stabilizerGroup`
- The four logical operators, their (anti)commutation, centralizer membership
- `StabilizerCode 4 2` + `StabilizerCodeWithLogicals 4 2`
- Distance 2 (weight-1 anti-witness against `ZZZZ` / `XXXX`)
-/

open NQubitPauliGroupElement

/-! ## Generators -/

/-- Z-check stabilizer: `ZZZZ` (Z on every qubit). -/
def Z1 : NQubitPauliGroupElement 4 := σ[ZZZZ]

/-- X-check stabilizer: `XXXX` (X on every qubit). -/
def X1 : NQubitPauliGroupElement 4 := σ[XXXX]

/-- The generator list (canonical order: Z-check first, then X-check). -/
def generatorsList : List (NQubitPauliGroupElement 4) :=
  [Z1, X1]

/-! ## Decided hypotheses

`ZZZZ` and `XXXX` overlap at all 4 qubits, so they anticommute pairwise at all 4
positions — count is 4 (even) ⇒ commute. `decide` checks the four ordered
pairs, the phases, and the check-matrix rank. -/

/-- All generators of the [[4, 2, 2]] code pairwise commute. -/
theorem generators_commute :
    ∀ g ∈ listToSet generatorsList, ∀ h ∈ listToSet generatorsList, g * h = h * g := by
  decide

/-- All generators have phase 0 (no `i` or `−1` factor). -/
lemma AllPhaseZero_generatorsList : AllPhaseZero generatorsList := by
  decide

/-- The check-matrix rows of the two generators are linearly independent over
ℤ/2. -/
theorem rowsLinearIndependent_generatorsList :
    rowsLinearIndependent generatorsList := by decide

/-- The generator list is an independent generating set. -/
theorem GeneratorsIndependent_4_generatorsList :
    GeneratorsIndependent 4 generatorsList :=
  GeneratorsIndependent_of_rowsLinearIndependent rowsLinearIndependent_generatorsList

/-! ## No `-I` in the stabilizer subgroup -/

/-- The closure of the two generators does not contain `-I`. -/
theorem negIdentity_not_mem :
    negIdentity 4 ∉ Subgroup.closure (listToSet generatorsList) :=
  negIdentity_not_mem_of_indep_phase_zero_commute generatorsList
    AllPhaseZero_generatorsList rowsLinearIndependent_generatorsList generators_commute

/-! ## Bundled `StabilizerGroup 4` -/

/-- The [[4, 2, 2]] stabilizer group, from the generator list. -/
noncomputable def stabilizerGroup : StabilizerGroup 4 :=
  mkStabilizerFromGenerators 4 generatorsList generators_commute negIdentity_not_mem

/-- The stabilizer subgroup is the closure of the generator list. -/
lemma stabilizerGroup_toSubgroup_eq :
    stabilizerGroup.toSubgroup = Subgroup.closure (listToSet generatorsList) := rfl

/-! ## Logical operators

The four logical operators consistent with the codeword basis above:
- `X̄₁ = IXIX` (flips logical bit 1)
- `X̄₂ = IIXX` (flips logical bit 2)
- `Z̄₁ = IIZZ` (measures logical bit 1)
- `Z̄₂ = IZIZ` (measures logical bit 2)
-/

/-- Logical X for logical qubit 1: `IXIX`. -/
def logicalX_1 : NQubitPauliGroupElement 4 := σ[IXIX]

/-- Logical X for logical qubit 2: `IIXX`. -/
def logicalX_2 : NQubitPauliGroupElement 4 := σ[IIXX]

/-- Logical Z for logical qubit 1: `IIZZ`. -/
def logicalZ_1 : NQubitPauliGroupElement 4 := σ[IIZZ]

/-- Logical Z for logical qubit 2: `IZIZ`. -/
def logicalZ_2 : NQubitPauliGroupElement 4 := σ[IZIZ]

/-! ### Diagonal anticommutation: X̄_ℓ anticommutes Z̄_ℓ -/

/-- `X̄₁` and `Z̄₁` anticommute (overlap at qubit 3 only — odd parity). -/
theorem logicalX_1_anticommutes_logicalZ_1 :
    NQubitPauliGroupElement.Anticommute logicalX_1 logicalZ_1 := by
  classical
  pauli_anticomm_odd_anticommutes
  have hfilter :
      (Finset.univ.filter
            (NQubitPauliGroupElement.anticommutesAt (n := 4)
              logicalX_1.operators logicalZ_1.operators)) =
        ({3} : Finset (Fin 4)) := by
    ext i; fin_cases i <;>
      simp [Finset.mem_filter, NQubitPauliGroupElement.anticommutesAt, logicalX_1, logicalZ_1,
        NQubitPauliOperator.set, NQubitPauliOperator.identity, PauliOperator.mulOp]
  rw [hfilter]; decide

/-- `X̄₂` and `Z̄₂` anticommute (overlap at qubit 3 only — odd parity). -/
theorem logicalX_2_anticommutes_logicalZ_2 :
    NQubitPauliGroupElement.Anticommute logicalX_2 logicalZ_2 := by
  classical
  pauli_anticomm_odd_anticommutes
  have hfilter :
      (Finset.univ.filter
            (NQubitPauliGroupElement.anticommutesAt (n := 4)
              logicalX_2.operators logicalZ_2.operators)) =
        ({3} : Finset (Fin 4)) := by
    ext i; fin_cases i <;>
      simp [Finset.mem_filter, NQubitPauliGroupElement.anticommutesAt, logicalX_2, logicalZ_2,
        NQubitPauliOperator.set, NQubitPauliOperator.identity, PauliOperator.mulOp]
  rw [hfilter]; decide

/-! ### Off-diagonal logical commutation (the k = 2 novelty) -/

/-- `X̄₁` and `X̄₂` commute (both X-type — trivial). -/
theorem logicalX_1_commutes_logicalX_2 :
    logicalX_1 * logicalX_2 = logicalX_2 * logicalX_1 := by
  pauli_comm_componentwise [logicalX_1, logicalX_2]

/-- `X̄₁` and `Z̄₂` commute (anticommute at qubits 1 and 3, count 2 = even). -/
theorem logicalX_1_commutes_logicalZ_2 :
    logicalX_1 * logicalZ_2 = logicalZ_2 * logicalX_1 := by
  classical
  pauli_comm_even_anticommutes
  have hfilter :
      (Finset.univ.filter
            (NQubitPauliGroupElement.anticommutesAt (n := 4)
              logicalX_1.operators logicalZ_2.operators)) =
        ({1, 3} : Finset (Fin 4)) := by
    ext i; fin_cases i <;>
      simp [Finset.mem_filter, NQubitPauliGroupElement.anticommutesAt, logicalX_1, logicalZ_2,
        NQubitPauliOperator.set, NQubitPauliOperator.identity, PauliOperator.mulOp]
  rw [hfilter]; decide

/-- `X̄₂` and `Z̄₁` commute (anticommute at qubits 2 and 3, count 2 = even). -/
theorem logicalX_2_commutes_logicalZ_1 :
    logicalX_2 * logicalZ_1 = logicalZ_1 * logicalX_2 := by
  classical
  pauli_comm_even_anticommutes
  have hfilter :
      (Finset.univ.filter
            (NQubitPauliGroupElement.anticommutesAt (n := 4)
              logicalX_2.operators logicalZ_1.operators)) =
        ({2, 3} : Finset (Fin 4)) := by
    ext i; fin_cases i <;>
      simp [Finset.mem_filter, NQubitPauliGroupElement.anticommutesAt, logicalX_2, logicalZ_1,
        NQubitPauliOperator.set, NQubitPauliOperator.identity, PauliOperator.mulOp]
  rw [hfilter]; decide

/-- `Z̄₁` and `Z̄₂` commute (both Z-type — trivial). -/
theorem logicalZ_1_commutes_logicalZ_2 :
    logicalZ_1 * logicalZ_2 = logicalZ_2 * logicalZ_1 := by
  pauli_comm_componentwise [logicalZ_1, logicalZ_2]

/-! ### Logical operators are in the centralizer -/

private lemma logicalX_1_commutes_Z1 : logicalX_1 * Z1 = Z1 * logicalX_1 := by
  classical
  pauli_comm_even_anticommutes
  have hfilter :
      (Finset.univ.filter
            (NQubitPauliGroupElement.anticommutesAt (n := 4)
              logicalX_1.operators Z1.operators)) =
        ({1, 3} : Finset (Fin 4)) := by
    ext i; fin_cases i <;>
      simp [Finset.mem_filter, NQubitPauliGroupElement.anticommutesAt, logicalX_1, Z1,
        NQubitPauliOperator.set, NQubitPauliOperator.identity, PauliOperator.mulOp]
  rw [hfilter]; decide

private lemma logicalX_1_commutes_X1 : logicalX_1 * X1 = X1 * logicalX_1 := by
  pauli_comm_componentwise [logicalX_1, X1]

private lemma logicalX_2_commutes_Z1 : logicalX_2 * Z1 = Z1 * logicalX_2 := by
  classical
  pauli_comm_even_anticommutes
  have hfilter :
      (Finset.univ.filter
            (NQubitPauliGroupElement.anticommutesAt (n := 4)
              logicalX_2.operators Z1.operators)) =
        ({2, 3} : Finset (Fin 4)) := by
    ext i; fin_cases i <;>
      simp [Finset.mem_filter, NQubitPauliGroupElement.anticommutesAt, logicalX_2, Z1,
        NQubitPauliOperator.set, NQubitPauliOperator.identity, PauliOperator.mulOp]
  rw [hfilter]; decide

private lemma logicalX_2_commutes_X1 : logicalX_2 * X1 = X1 * logicalX_2 := by
  pauli_comm_componentwise [logicalX_2, X1]

private lemma logicalZ_1_commutes_Z1 : logicalZ_1 * Z1 = Z1 * logicalZ_1 := by
  pauli_comm_componentwise [logicalZ_1, Z1]

private lemma logicalZ_1_commutes_X1 : logicalZ_1 * X1 = X1 * logicalZ_1 := by
  classical
  pauli_comm_even_anticommutes
  have hfilter :
      (Finset.univ.filter
            (NQubitPauliGroupElement.anticommutesAt (n := 4)
              logicalZ_1.operators X1.operators)) =
        ({2, 3} : Finset (Fin 4)) := by
    ext i; fin_cases i <;>
      simp [Finset.mem_filter, NQubitPauliGroupElement.anticommutesAt, logicalZ_1, X1,
        NQubitPauliOperator.set, NQubitPauliOperator.identity, PauliOperator.mulOp]
  rw [hfilter]; decide

private lemma logicalZ_2_commutes_Z1 : logicalZ_2 * Z1 = Z1 * logicalZ_2 := by
  pauli_comm_componentwise [logicalZ_2, Z1]

private lemma logicalZ_2_commutes_X1 : logicalZ_2 * X1 = X1 * logicalZ_2 := by
  classical
  pauli_comm_even_anticommutes
  have hfilter :
      (Finset.univ.filter
            (NQubitPauliGroupElement.anticommutesAt (n := 4)
              logicalZ_2.operators X1.operators)) =
        ({1, 3} : Finset (Fin 4)) := by
    ext i; fin_cases i <;>
      simp [Finset.mem_filter, NQubitPauliGroupElement.anticommutesAt, logicalZ_2, X1,
        NQubitPauliOperator.set, NQubitPauliOperator.identity, PauliOperator.mulOp]
  rw [hfilter]; decide

/-- `X̄₁ = IXIX` commutes with every element of the stabilizer (vs. `ZZZZ` even
overlap at qubits 1, 3; vs. `XXXX` all X — both commute). -/
theorem logicalX_1_mem_centralizer :
    logicalX_1 ∈ centralizer stabilizerGroup := by
  rw [StabilizerGroup.mem_centralizer_iff_closure _ _ _ stabilizerGroup_toSubgroup_eq]
  intro s hs
  simp only [generatorsList, listToSet_cons, listToSet_nil, Set.mem_insert_iff,
    Set.mem_empty_iff_false, or_false] at hs
  rcases hs with rfl | rfl
  · exact logicalX_1_commutes_Z1.symm
  · exact logicalX_1_commutes_X1.symm

/-- `X̄₂ = IIXX` commutes with every element of the stabilizer. -/
theorem logicalX_2_mem_centralizer :
    logicalX_2 ∈ centralizer stabilizerGroup := by
  rw [StabilizerGroup.mem_centralizer_iff_closure _ _ _ stabilizerGroup_toSubgroup_eq]
  intro s hs
  simp only [generatorsList, listToSet_cons, listToSet_nil, Set.mem_insert_iff,
    Set.mem_empty_iff_false, or_false] at hs
  rcases hs with rfl | rfl
  · exact logicalX_2_commutes_Z1.symm
  · exact logicalX_2_commutes_X1.symm

/-- `Z̄₁ = IIZZ` commutes with every element of the stabilizer. -/
theorem logicalZ_1_mem_centralizer :
    logicalZ_1 ∈ centralizer stabilizerGroup := by
  rw [StabilizerGroup.mem_centralizer_iff_closure _ _ _ stabilizerGroup_toSubgroup_eq]
  intro s hs
  simp only [generatorsList, listToSet_cons, listToSet_nil, Set.mem_insert_iff,
    Set.mem_empty_iff_false, or_false] at hs
  rcases hs with rfl | rfl
  · exact logicalZ_1_commutes_Z1.symm
  · exact logicalZ_1_commutes_X1.symm

/-- `Z̄₂ = IZIZ` commutes with every element of the stabilizer. -/
theorem logicalZ_2_mem_centralizer :
    logicalZ_2 ∈ centralizer stabilizerGroup := by
  rw [StabilizerGroup.mem_centralizer_iff_closure _ _ _ stabilizerGroup_toSubgroup_eq]
  intro s hs
  simp only [generatorsList, listToSet_cons, listToSet_nil, Set.mem_insert_iff,
    Set.mem_empty_iff_false, or_false] at hs
  rcases hs with rfl | rfl
  · exact logicalZ_2_commutes_Z1.symm
  · exact logicalZ_2_commutes_X1.symm

/-! ## StabilizerCode packaging [[4, 2]] -/

/-- The two-logical-qubit `LogicalQubitOps` family. -/
private def logicalOps4_2_2 : Fin 2 → LogicalQubitOps 4 stabilizerGroup := fun ℓ =>
  match ℓ with
  | 0 => ⟨logicalX_1, logicalZ_1,
            logicalX_1_mem_centralizer, logicalZ_1_mem_centralizer,
            logicalX_1_anticommutes_logicalZ_1⟩
  | 1 => ⟨logicalX_2, logicalZ_2,
            logicalX_2_mem_centralizer, logicalZ_2_mem_centralizer,
            logicalX_2_anticommutes_logicalZ_2⟩

/-- The [[4, 2, 2]] code as a stabilizer code on 4 physical qubits with 2
logical qubits. -/
noncomputable def stabilizerCode : StabilizerCode 4 2 where
  hk := by decide
  generatorsList := generatorsList
  generators_length := rfl
  generators_phaseZero := AllPhaseZero_generatorsList
  generators_independent := GeneratorsIndependent_4_generatorsList
  generators_commute := generators_commute
  closure_no_neg_identity := negIdentity_not_mem

/-- The [[4, 2, 2]] code packaged with its logical basis `(X̄₁, Z̄₁)`,
`(X̄₂, Z̄₂)` (`logicalX_1`/`logicalZ_1`, `logicalX_2`/`logicalZ_2`). -/
noncomputable def stabilizerCodeWithLogicals : StabilizerCodeWithLogicals 4 2 where
  toStabilizerCode := stabilizerCode
  logicalOps := logicalOps4_2_2
  logical_commute_cross := by
    intro ℓ ℓ' hne
    fin_cases ℓ <;> fin_cases ℓ'
    · exact (hne rfl).elim
    · refine ⟨logicalX_1_commutes_logicalX_2, logicalX_1_commutes_logicalZ_2, ?_, ?_⟩
      · exact logicalX_2_commutes_logicalZ_1.symm
      · exact logicalZ_1_commutes_logicalZ_2
    · refine ⟨logicalX_1_commutes_logicalX_2.symm, logicalX_2_commutes_logicalZ_1, ?_, ?_⟩
      · exact logicalX_1_commutes_logicalZ_2.symm
      · exact logicalZ_1_commutes_logicalZ_2.symm
    · exact (hne rfl).elim

/-! ## Code distance = 2 -/

/-- The stabilizer-code subgroup equals the closure of the generator list. -/
private lemma stabilizerCode_toSubgroup_eq :
    stabilizerCode.toStabilizerGroup.toSubgroup = Subgroup.closure (listToSet generatorsList) :=
  rfl

/-- Helper: a weight-1 Pauli with local Pauli `P` at qubit `i` anticommutes with
the all-Z stabilizer `Z1` provided `P ∈ {X, Y}` (the cases where Z anticommutes
locally). -/
private lemma weightOneAt_anticomm_Z1 (i : Fin 4) (P : PauliOperator)
    (hP : P = PauliOperator.X ∨ P = PauliOperator.Y) :
    NQubitPauliGroupElement.Anticommute (weightOneAt i P) Z1 := by
  classical
  pauli_anticomm_odd_anticommutes
  have hfilter :
      (Finset.univ.filter
            (NQubitPauliGroupElement.anticommutesAt (n := 4)
              (weightOneAt i P).operators Z1.operators)) =
        ({i} : Finset (Fin 4)) := by
    ext j; fin_cases i <;> fin_cases j <;>
      rcases hP with rfl | rfl <;>
        simp [Finset.mem_filter, NQubitPauliGroupElement.anticommutesAt,
          weightOneAt, NQubitPauliGroupElement.ofOperator,
          Z1, NQubitPauliOperator.set, PauliOperator.mulOp]
  rw [hfilter]; simp +decide

/-- Helper: a weight-1 Pauli with local Pauli `Z` at qubit `i` anticommutes with
the all-X stabilizer `X1`. -/
private lemma weightOneAt_Z_anticomm_X1 (i : Fin 4) :
    NQubitPauliGroupElement.Anticommute (weightOneAt i PauliOperator.Z) X1 := by
  classical
  pauli_anticomm_odd_anticommutes
  have hfilter :
      (Finset.univ.filter
            (NQubitPauliGroupElement.anticommutesAt (n := 4)
              (weightOneAt i PauliOperator.Z).operators X1.operators)) =
        ({i} : Finset (Fin 4)) := by
    ext j; fin_cases i <;> fin_cases j <;>
      simp [Finset.mem_filter, NQubitPauliGroupElement.anticommutesAt,
        weightOneAt, NQubitPauliGroupElement.ofOperator,
        X1, NQubitPauliOperator.set, PauliOperator.mulOp]
  rw [hfilter]; simp +decide

/-- Anticommute witness for the [[4,2,2]] code: every weight-1 Pauli
anticommutes with either `ZZZZ` (when the local Pauli is X or Y) or `XXXX` (when
the local Pauli is Z). -/
private lemma weight_one_anticomm_witness :
    ∀ i : Fin 4, ∀ P : PauliOperator, P ≠ PauliOperator.I →
      ∃ g ∈ listToSet generatorsList, NQubitPauliGroupElement.Anticommute
        (weightOneAt i P) g := by
  intro i P hP
  match P, hP with
  | PauliOperator.X, _ =>
    exact ⟨Z1, by simp [generatorsList], weightOneAt_anticomm_Z1 i _ (Or.inl rfl)⟩
  | PauliOperator.Y, _ =>
    exact ⟨Z1, by simp [generatorsList], weightOneAt_anticomm_Z1 i _ (Or.inr rfl)⟩
  | PauliOperator.Z, _ =>
    exact ⟨X1, by simp [generatorsList], weightOneAt_Z_anticomm_X1 i⟩
  | PauliOperator.I, hP => exact (hP rfl).elim

/-- The [[4, 2, 2]] code has distance 2: every weight-1 single-qubit Pauli
anticommutes with at least one of `ZZZZ` or `XXXX`, and `X̄₁ = IXIX` is a
nontrivial logical operator of weight exactly 2. -/
theorem code_has_distance_two : HasCodeDistance stabilizerCode 2 :=
  hasCodeDistance_two_of_anticommute_witness stabilizerCode (listToSet generatorsList)
    stabilizerCode_toSubgroup_eq weight_one_anticomm_witness
    ⟨logicalX_1, (logicalOps4_2_2 0).xOp_nontrivial, by decide⟩

/-- The [[4, 2, 2]] code packaged with its distance. -/
noncomputable def stabilizerCodeWithDistance : StabilizerCodeWithDistance 4 2 2 where
  toStabilizerCode := stabilizerCode
  hasDistance      := code_has_distance_two

end FourQubit_4_2_2
end StabilizerGroup
end Quantum
