import Mathlib.Tactic
import QEC.Stabilizer.Framework.Core.Stabilizer.StabilizerGroup
import QEC.Stabilizer.Framework.Core.Stabilizer.SubgroupLemmas
import QEC.Stabilizer.Framework.Core.Stabilizer.Centralizer
import QEC.Stabilizer.Foundations.PauliGroup.Commutation
import QEC.Stabilizer.Foundations.PauliGroup.CommutationTactics
import QEC.Stabilizer.Foundations.BinarySymplectic.Core
import QEC.Stabilizer.Foundations.BinarySymplectic.CheckMatrix
import QEC.Stabilizer.Foundations.BinarySymplectic.CheckMatrixDecidable
import QEC.Stabilizer.Framework.Symplectic.SymplecticSpan
import QEC.Stabilizer.Framework.Core.Stabilizer.StabilizerCode
import QEC.Stabilizer.Framework.Core.CodeNotation
import QEC.Stabilizer.Framework.Symplectic.IndependentEquiv
import QEC.Stabilizer.Foundations.BinarySymplectic.SymplecticInner
import QEC.Stabilizer.Foundations.PauliGroup.NQubitOperator

namespace Quantum
open scoped BigOperators
open scoped Pauli

namespace StabilizerGroup
namespace Steane7

/-!
# The Steane [[7,1,3]] code (CSS stabilizer generators)

We use the standard CSS presentation coming from the classical [7,4,3] Hamming
code.

Let the parity-check rows (supports) be:
- r₁ = {0,1,2,4}
- r₂ = {0,1,3,5}
- r₃ = {0,2,3,6}

Then the Steane stabilizer is generated by:
- Z-checks: Z on each row support (3 generators)
- X-checks: X on each row support (3 generators)

The code is packaged by the **decide route**: the six generators form a
literal list, and every hypothesis of `Code[[7, 1]]` — pairwise commutation,
phase zero, linear independence of the check-matrix rows — is a closed
decidable statement that the kernel settles with `decide`. `−I ∉ closure`
then follows from `negIdentity_not_mem_of_indep_phase_zero_commute` without
any Z/X typing argument (the CSS structure is still visible in the generator
names, and `Steane7Distance.lean` uses it for the distance bound).

## Outline

- Generators `Z1`–`Z3`, `X1`–`X3` and the list `generatorsList`
- Decided hypotheses: `generators_commute`, `AllPhaseZero_generatorsList`,
  `rowsLinearIndependent_generatorsList`
- `negIdentity_not_mem`, the bundled `stabilizerGroup`
- Logical operators `X̄ = X⊗⁷`, `Z̄ = Z⊗⁷` (and `Ȳ = i X̄ Z̄`)
- `stabilizerCode : Code[[7, 1]]` and `stabilizerCodeWithLogicals`
-/

open NQubitPauliGroupElement

/-!
## Generators
-/

/-- Z-check on row r₁ = {0,1,2,4}: Z on qubits 0,1,2,4 and I elsewhere. -/
def Z1 : NQubitPauliGroupElement 7 := σ[ZZZIZII]

/-- Z-check on row r₂ = {0,1,3,5}: Z on qubits 0,1,3,5 and I elsewhere. -/
def Z2 : NQubitPauliGroupElement 7 := σ[ZZIZIZI]

/-- Z-check on row r₃ = {0,2,3,6}: Z on qubits 0,2,3,6 and I elsewhere. -/
def Z3 : NQubitPauliGroupElement 7 := σ[ZIZZIIZ]

/-- X-check on row r₁ = {0,1,2,4}: X on qubits 0,1,2,4 and I elsewhere. -/
def X1 : NQubitPauliGroupElement 7 := σ[XXXIXII]

/-- X-check on row r₂ = {0,1,3,5}: X on qubits 0,1,3,5 and I elsewhere. -/
def X2 : NQubitPauliGroupElement 7 := σ[XXIXIXI]

/-- X-check on row r₃ = {0,2,3,6}: X on qubits 0,2,3,6 and I elsewhere. -/
def X3 : NQubitPauliGroupElement 7 := σ[XIXXIIX]

/-- The six generators as a list (Z-checks first, then X-checks). This is the
single source of truth for the stabilizer group and the `StabilizerCode`. -/
def generatorsList : List (NQubitPauliGroupElement 7) :=
  [Z1, Z2, Z3, X1, X2, X3]

/-!
## Decided hypotheses

Each statement below is a finite conjunction of closed facts about literal
group elements, so `decide` closes it through the global
`DecidableEq (NQubitPauliGroupElement n)` instance. Mathematically, a Z-row
and an X-row meet in an even number of qubits (`r₁ ∩ r₂ = {0, 1}`,
`r₁ ∩ r₃ = {0, 2}`, `r₂ ∩ r₃ = {0, 3}`, and each row with itself in four), and
same-type generators commute componentwise.
-/

/-- All six generators pairwise commute. -/
theorem generators_commute :
    ∀ g ∈ listToSet generatorsList, ∀ h ∈ listToSet generatorsList, g * h = h * g := by
  decide

/-- Every element of the generators list has phase power 0. -/
lemma AllPhaseZero_generatorsList : AllPhaseZero generatorsList := by
  decide

/-- The check-matrix rows of the Steane generators are linearly independent. -/
theorem rowsLinearIndependent_generatorsList :
    rowsLinearIndependent generatorsList := by decide

/-- The Steane generator list is an independent generating set. -/
theorem GeneratorsIndependent_7_generatorsList : GeneratorsIndependent 7 generatorsList :=
  GeneratorsIndependent_of_rowsLinearIndependent rowsLinearIndependent_generatorsList

/-!
## No `-I` in the Steane stabilizer subgroup
-/

/-- The closure of the six generators does not contain −I: they are phase-0,
pairwise commuting, and symplectically independent. -/
theorem negIdentity_not_mem : negIdentity 7 ∉ Subgroup.closure (listToSet generatorsList) :=
  negIdentity_not_mem_of_indep_phase_zero_commute generatorsList
    AllPhaseZero_generatorsList rowsLinearIndependent_generatorsList generators_commute

/-!
## Bundled `StabilizerGroup 7`
-/

/-- Steane code as `StabilizerGroup 7` (canonical: from generator list). -/
noncomputable def stabilizerGroup : StabilizerGroup 7 :=
  mkStabilizerFromGenerators 7 generatorsList generators_commute negIdentity_not_mem

/-- The stabilizer subgroup is the closure of the generator list. -/
lemma stabilizerGroup_toSubgroup_eq :
    stabilizerGroup.toSubgroup = Subgroup.closure (listToSet generatorsList) := rfl

/-!
## Logical operators

Logical X = X on all 7 qubits, logical Z = Z on all 7 qubits. They commute with
the stabilizer and anticommute with each other.
-/

/-- Logical X: X on all seven qubits. -/
def logicalX : NQubitPauliGroupElement 7 :=
  ⟨0, NQubitPauliOperator.X 7⟩

/-- Logical Z: Z on all seven qubits. -/
def logicalZ : NQubitPauliGroupElement 7 :=
  ⟨0, NQubitPauliOperator.Z 7⟩

/-- Logical Y with the convention `Ȳ = i X̄ Z̄`. -/
noncomputable def logicalY : NQubitPauliGroupElement 7 :=
  NQubitPauliGroupElement.phaseI 7 * (logicalX * logicalZ)

/-- Steane logical `Ȳ` is phase-2 all-`Y`, under the convention `Ȳ = i X̄ Z̄`.
-/
lemma logicalY_eq_phase2_allY :
    logicalY = ({ phasePower := (2 : Fin 4), operators := NQubitPauliOperator.Y 7 } :
      NQubitPauliGroupElement 7) := by
  decide

/-- Logical X and logical Z anticommute (symplectic inner product 1 mod 2). -/
theorem logicalX_anticommutes_logicalZ : NQubitPauliGroupElement.Anticommute logicalX logicalZ :=
  NQubitPauliOperator.allX_allZ_anticommute 7 (by decide)

/-- Logical X commutes with every element of the stabilizer: it suffices to
check the six generators, each a closed identity settled by `decide`. -/
theorem logicalX_mem_centralizer : logicalX ∈ centralizer stabilizerGroup := by
  rw [StabilizerGroup.mem_centralizer_iff_closure _ _ _ stabilizerGroup_toSubgroup_eq]
  intro s hs
  simp only [generatorsList, listToSet_cons, listToSet_nil, Set.mem_insert_iff,
    Set.mem_empty_iff_false, or_false] at hs
  rcases hs with rfl | rfl | rfl | rfl | rfl | rfl <;> decide

/-- Logical Z commutes with every element of the stabilizer (same argument as
`logicalX_mem_centralizer`). -/
theorem logicalZ_mem_centralizer : logicalZ ∈ centralizer stabilizerGroup := by
  rw [StabilizerGroup.mem_centralizer_iff_closure _ _ _ stabilizerGroup_toSubgroup_eq]
  intro s hs
  simp only [generatorsList, listToSet_cons, listToSet_nil, Set.mem_insert_iff,
    Set.mem_empty_iff_false, or_false] at hs
  rcases hs with rfl | rfl | rfl | rfl | rfl | rfl <;> decide

/-!
## StabilizerCode [[7, 1]]

The bare code is its stabilizer group: six independent, pairwise commuting
generators on seven qubits, hence one logical qubit. The chosen logical pair
`(X̄, Z̄)` is bundled separately, in `stabilizerCodeWithLogicals`.
-/

/-- The Steane code as a stabilizer code [[7, 1]]: one logical qubit. -/
noncomputable def stabilizerCode : Code[[7, 1]] where
  hk := by decide
  generatorsList := generatorsList
  generators_length := rfl
  generators_phaseZero := AllPhaseZero_generatorsList
  generators_independent := GeneratorsIndependent_7_generatorsList
  generators_commute := generators_commute
  closure_no_neg_identity := negIdentity_not_mem

/-- The Steane code with its canonical logical basis `X̄ = X⊗⁷`, `Z̄ = Z⊗⁷`. -/
noncomputable def stabilizerCodeWithLogicals : Code[[7, 1]]ₗ where
  toStabilizerCode := stabilizerCode
  logicalOps := fun _ =>
    ⟨logicalX, logicalZ, logicalX_mem_centralizer, logicalZ_mem_centralizer,
      logicalX_anticommutes_logicalZ⟩
  logical_commute_cross := fun ℓ ℓ' h => (h (Subsingleton.elim ℓ ℓ')).elim

end Steane7
end StabilizerGroup

end Quantum
