import QEC.Stabilizer.Framework.Core.Stabilizer.StabilizerGroup
import QEC.Stabilizer.Framework.Core.Stabilizer.Centralizer
import QEC.Stabilizer.Foundations.PauliGroup.NQubitOperator
import QEC.Stabilizer.Foundations.PauliGroup.NQubitElement
import QEC.Stabilizer.Foundations.PauliGroup.Commutation
import QEC.Stabilizer.Foundations.PauliGroupSingle

namespace Quantum
namespace StabilizerGroup

variable {n : ℕ}

open NQubitPauliGroupElement
open PauliOperator

/-!
# CSS code distance helpers

If for every qubit and every non-identity single-qubit Pauli at that qubit there is a
generator that anticommutes with the corresponding weight-1 element, then no weight-1
Pauli lies in the centralizer. This is used to prove no weight-1 logicals for CSS codes.
-/

/-- The weight-1 group element at qubit `i` with single-qubit Pauli `P` (phase 0). -/
def weightOneAt (i : Fin n) (P : PauliOperator) : NQubitPauliGroupElement n :=
  ofOperator (fun k => if k = i then P else .I)

/-- If for every qubit `i` and every single-qubit Pauli `P ≠ I` there exists a generator
    in `genSet` that anticommutes with the weight-1 element at `i` with Pauli `P`, then
    no weight-1 Pauli is in the centralizer of the stabilizer group generated by `genSet`. -/
theorem no_weight_one_mem_centralizer_of_anticommute_witness (S : StabilizerGroup n)
    (genSet : Set (NQubitPauliGroupElement n))
    (h_closure : S.toSubgroup = Subgroup.closure genSet)
    (h_anticomm : ∀ i : Fin n, ∀ P : PauliOperator, P ≠ .I →
      ∃ g ∈ genSet, Anticommute (weightOneAt i P) g)
    (g : NQubitPauliGroupElement n) (hg : weight g = 1)
    (h_cent : g ∈ centralizer S) : False := by
  rw [mem_centralizer_iff_closure g S genSet h_closure] at h_cent
  have h_supp_card : (support g).card = 1 := by
    rw [support, ← NQubitPauliOperator.weight, ← weight]; exact hg
  obtain ⟨i, hi⟩ := Finset.card_eq_one.mp h_supp_card
  have hi_supp : support g = {i} := hi
  have hi_ne_I : g.operators i ≠ .I := by
    have : i ∈ support g := by rw [hi_supp]; exact Finset.mem_singleton_self i
    exact (mem_support g i).mp this
  have hop : g.operators = fun k => if k = i then g.operators i else .I := by
    ext k
    by_cases hk : k = i
    · simp [hk]
    · have hk' : k ∉ support g := by rw [hi_supp, Finset.mem_singleton]; exact hk
      have h_op_k : g.operators k = .I := by by_contra h; exact hk' ((mem_support g k).mpr h)
      simp only [hk, if_false, h_op_k]
  obtain ⟨s, hs_mem, h_anti⟩ := h_anticomm i (g.operators i) hi_ne_I
  have heq : g.operators = (weightOneAt i (g.operators i)).operators := by
    simp only [weightOneAt, ofOperator_operators]; exact hop
  have h_anti_g : Anticommute g s := by
    rw [anticommutes_iff_mulOp_phasePower] at h_anti
    rw [anticommutes_iff_mulOp_phasePower]; rw [heq]; exact h_anti
  have h_comm : s * g = g * s := h_cent s hs_mem
  unfold Anticommute at h_anti_g
  rw [← h_comm, ← negIdentity_eq_minusOne n] at h_anti_g
  have h_neg : negIdentity n = 1 := by
    have H : (s * g) = negIdentity n * (s * g) := h_anti_g
    calc negIdentity n = negIdentity n * 1 := (NQubitPauliGroupElement.mul_one _).symm
      _ = negIdentity n * ((s * g) * (s * g)⁻¹) := by rw [mul_inv_cancel]
      _ = (negIdentity n * (s * g)) * (s * g)⁻¹ := by
          rw [NQubitPauliGroupElement.mul_assoc (negIdentity n) (s * g) (s * g)⁻¹]
      _ = (s * g) * (s * g)⁻¹ := by rw [← H]
      _ = 1 := by rw [mul_inv_cancel]
  exact negIdentity_ne_one n h_neg

/-! ## Weight-2 anticommute witness

Mirror of the weight-1 helper above for distance-3 codes (where ruling out
weight-1 *and* weight-2 logicals is required). The shape is the same: given
a witness function from qubit-pairs and Pauli-pairs to generators that
anticommute with the corresponding weight-2 element, conclude no weight-2
Pauli lies in the centralizer.

First exerciser: the [[5,1,3]] five-qubit perfect code in
`Codes/FiveQubit_5_1_3.lean`. -/

/-- The weight-2 group element at qubits `i ≠ j` with single-qubit Paulis
`P` at qubit `i` and `Q` at qubit `j` (phase 0). -/
def weightTwoAt (i j : Fin n) (P Q : PauliOperator) : NQubitPauliGroupElement n :=
  ofOperator (fun k => if k = i then P else if k = j then Q else .I)

/-- If for every pair of distinct qubits `i ≠ j` and every pair of
non-identity single-qubit Paulis `P, Q` there exists a generator in
`genSet` that anticommutes with the corresponding weight-2 element, then
no weight-2 Pauli is in the centralizer of the stabilizer group generated
by `genSet`. -/
theorem no_weight_two_mem_centralizer_of_anticommute_witness (S : StabilizerGroup n)
    (genSet : Set (NQubitPauliGroupElement n))
    (h_closure : S.toSubgroup = Subgroup.closure genSet)
    (h_anticomm : ∀ i j : Fin n, i ≠ j → ∀ P Q : PauliOperator, P ≠ .I → Q ≠ .I →
      ∃ g ∈ genSet, Anticommute (weightTwoAt i j P Q) g)
    (g : NQubitPauliGroupElement n) (hg : weight g = 2)
    (h_cent : g ∈ centralizer S) : False := by
  rw [mem_centralizer_iff_closure g S genSet h_closure] at h_cent
  have h_supp_card : (support g).card = 2 := by
    rw [support, ← NQubitPauliOperator.weight, ← weight]; exact hg
  obtain ⟨i, j, hij, hsupp⟩ := Finset.card_eq_two.mp h_supp_card
  -- g.operators are non-identity at i and j, identity elsewhere
  have hi_ne_I : g.operators i ≠ .I := by
    have : i ∈ support g := by rw [hsupp]; exact Finset.mem_insert_self i {j}
    exact (mem_support g i).mp this
  have hj_ne_I : g.operators j ≠ .I := by
    have : j ∈ support g := by rw [hsupp]; simp
    exact (mem_support g j).mp this
  have hop : g.operators =
      fun k => if k = i then g.operators i else if k = j then g.operators j else .I := by
    ext k
    by_cases hki : k = i
    · subst hki; simp
    · by_cases hkj : k = j
      · subst hkj; simp [hki]
      · have hk' : k ∉ support g := by
          rw [hsupp]; simp [hki, hkj]
        have h_op_k : g.operators k = .I := by
          by_contra h; exact hk' ((mem_support g k).mpr h)
        simp [hki, hkj, h_op_k]
  obtain ⟨s, hs_mem, h_anti⟩ := h_anticomm i j hij (g.operators i) (g.operators j) hi_ne_I hj_ne_I
  have heq : g.operators = (weightTwoAt i j (g.operators i) (g.operators j)).operators := by
    simp only [weightTwoAt, ofOperator_operators]; exact hop
  have h_anti_g : Anticommute g s := by
    rw [anticommutes_iff_mulOp_phasePower] at h_anti
    rw [anticommutes_iff_mulOp_phasePower]; rw [heq]; exact h_anti
  have h_comm : s * g = g * s := h_cent s hs_mem
  unfold Anticommute at h_anti_g
  rw [← h_comm, ← negIdentity_eq_minusOne n] at h_anti_g
  have h_neg : negIdentity n = 1 := by
    have H : (s * g) = negIdentity n * (s * g) := h_anti_g
    calc negIdentity n = negIdentity n * 1 := (NQubitPauliGroupElement.mul_one _).symm
      _ = negIdentity n * ((s * g) * (s * g)⁻¹) := by rw [mul_inv_cancel]
      _ = (negIdentity n * (s * g)) * (s * g)⁻¹ := by
          rw [NQubitPauliGroupElement.mul_assoc (negIdentity n) (s * g) (s * g)⁻¹]
      _ = (s * g) * (s * g)⁻¹ := by rw [← H]
      _ = 1 := by rw [mul_inv_cancel]
  exact negIdentity_ne_one n h_neg

end StabilizerGroup
end Quantum
