#!/usr/bin/env python3
"""
Apply manual audit corrections to ``catalog/scoring.yaml``.

This script is run after the qec-prioritizer agent when human review surfaces
overlaps the agent missed — typically named small instances of parametric
families that are already covered, or abstract base classes.

Each correction has:
- ``code_id``: target entry to patch
- ``new_status`` / ``new_track``: replacement values
- ``audit_note``: rationale (preserved in the entry's rationale field)

Run after every prioritizer pass; commit the resulting scoring.yaml.
"""

from __future__ import annotations

import sys
from pathlib import Path
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SCORING_PATH = REPO_ROOT / "catalog" / "scoring.yaml"

# Audit corrections — codes the prioritizer missed because they're named
# instances of an already-formalized parametric family, or abstract classes
# that already exist as repo infrastructure.
CORRECTIONS: list[dict] = [
    {
        "code_id": "surface-17",
        "new_status": "done",
        "new_track": "skip",
        "audit_note": (
            "Audit override: explicitly a [[9,1,3]] rotated surface code — "
            "the L=3 instance of QEC/Stabilizer/Codes/RotatedSurfaceCodeN.lean "
            "(with stabilizer-code packaging in RotatedSurfaceCodeNStabilizerCode.lean "
            "and distance proof in RotatedSurfaceCodeNDistance*.lean)."
        ),
    },
    {
        "code_id": "stab_5_1_2",
        "new_status": "out_of_scope",
        "new_track": "skip",
        "audit_note": (
            "Audit override: a [[5,1,2]] degenerate rotated-surface variant "
            "(\"rotated surface code on one rung of a ladder\"). The parametric "
            "RotatedSurfaceCodeN formalization requires [Fact (3 ≤ L)] and L odd, "
            "so this ladder-geometry variant is structurally outside the framework. "
            "Reclassified to skip; revisit if/when the framework is extended."
        ),
    },
    {
        "code_id": "qubit_stabilizer",
        "new_status": "done",
        "new_track": "skip",
        "audit_note": (
            "Audit override: the abstract qubit-stabilizer-code class. Already "
            "implemented as the Stabilizer/Core/StabilizerGroup + Stabilizer/Core/StabilizerCode "
            "infrastructure in this repo — not a concrete code to be formalized separately."
        ),
    },
    {
        "code_id": "stab_15_7_3",
        "new_status": "done",
        "new_track": "skip",
        "audit_note": (
            "Audit override: [[15,7,3]] is the r=4 instance of the quantum Hamming "
            "family [[2^r-1, 2^r-1-2r, 3]] that QEC/Stabilizer/Codes/QuantumHamming.lean "
            "defines parametrically for r ≥ 3."
        ),
    },
]


def main() -> int:
    with open(SCORING_PATH, encoding="utf-8") as f:
        data = yaml.safe_load(f)

    by_id = {e["code_id"]: e for e in data["entries"]}

    applied = 0
    missing: list[str] = []
    for c in CORRECTIONS:
        e = by_id.get(c["code_id"])
        if e is None:
            missing.append(c["code_id"])
            continue
        e["status"] = c["new_status"]
        e["proposed_track"] = c["new_track"]
        e["composite"] = -1.0
        existing = e.get("rationale", "")
        e["rationale"] = c["audit_note"] + (
            "\n\nPrevious rationale: " + existing if existing else ""
        )
        applied += 1

    # Refresh metadata counters
    statuses = [e.get("status") for e in data["entries"]]
    tracks = [e.get("proposed_track") for e in data["entries"]]
    data["metadata"]["done"] = sum(1 for s in statuses if s == "done")
    data["metadata"]["in_flight"] = sum(1 for s in statuses if s == "in_flight")
    data["metadata"]["not_started"] = sum(1 for s in statuses if s == "not_started")
    data["metadata"]["out_of_scope"] = sum(1 for s in statuses if s == "out_of_scope")
    data["metadata"]["audit_applied_on"] = "2026-05-22"
    data["metadata"]["audit_corrections"] = applied

    with open(SCORING_PATH, "w", encoding="utf-8") as f:
        f.write(
            "# Generated by qec-prioritizer: scoring of every catalog entry on six axes.\n"
            "# Composite = 0.25*reuse + 0.15*canon + 0.15*hardware + 0.15*tract + 0.20*prereq + 0.10*effort\n"
            "# Tracks: engineering | moonshot | defer | skip\n"
            "# Audit corrections applied via scripts/patch_scoring.py.\n\n"
        )
        yaml.safe_dump(data, f, sort_keys=False, allow_unicode=True, width=120)

    print(f"applied {applied} audit corrections")
    if missing:
        print(f"warning: code_ids not found: {missing}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
